import type {
  CardDef,
  CardId,
  ChapterId,
  EnemyDef,
  EnemyId,
  HeartDef,
  HeartId,
  HeroDef,
  Intent,
  TechniqueDef,
  TechniqueId,
} from "./types";
import { BASE_HP } from "./types";

export const CARDS: Record<CardId, CardDef> = {
  strike: {
    id: "strike",
    name: "劈掌",
    cost: 1,
    type: "attack",
    text: "造成 6 点伤害。",
    flavor: "推宫一门的见面礼。",
    damage: 6,
  },
  defend: {
    id: "defend",
    name: "卸力",
    cost: 1,
    type: "skill",
    text: "获得 8 点格挡。",
    flavor: "力从脚走。",
    block: 8,
  },
  push: {
    id: "push",
    name: "推宫",
    cost: 1,
    type: "attack",
    text: "击退 2 格。撞壁再受 8 点伤害。",
    flavor: "破门不问门闩。",
    knock: 2,
    wall: 8,
  },
  charge: {
    id: "charge",
    name: "蓄劲",
    cost: 1,
    type: "skill",
    text: "下一张攻击伤害 +4。",
    flavor: "一口气先压进小腹。",
    chargeBonus: 4,
  },
  advance: {
    id: "advance",
    name: "进步",
    cost: 0,
    type: "skill",
    text: "身前一格为空则前进，抽 1 张牌。",
    flavor: "七步之内。",
    steps: 1,
  },
  strike2: {
    id: "strike2",
    name: "开山掌",
    cost: 1,
    type: "attack",
    text: "造成 9 点伤害。",
    flavor: "掌风比刀快半寸。",
    damage: 9,
  },
  defend2: {
    id: "defend2",
    name: "卸力入骨",
    cost: 1,
    type: "skill",
    text: "获得 12 点格挡。",
    flavor: "力走进骨缝里。",
    block: 12,
  },
  push2: {
    id: "push2",
    name: "破门",
    cost: 1,
    type: "attack",
    text: "击退 3 格。撞壁再受 10 点伤害。",
    flavor: "门闩先走。",
    knock: 3,
    wall: 10,
  },
  charge2: {
    id: "charge2",
    name: "沉劲",
    cost: 1,
    type: "skill",
    text: "下一张攻击伤害 +7。",
    flavor: "气沉到脚底板。",
    chargeBonus: 7,
  },
  advance2: {
    id: "advance2",
    name: "纵步",
    cost: 0,
    type: "skill",
    text: "身前最多前进 2 格。抽 1 张牌。",
    flavor: "两步并作一步。",
    steps: 2,
  },
  drawcut: {
    id: "drawcut",
    name: "抽刀",
    cost: 1,
    type: "attack",
    text: "相邻则造成 9 点伤害，否则 4 点。",
    flavor: "刀还在鞘里时，人已经到了。",
    damage: 4,
  },
  backpalm: {
    id: "backpalm",
    name: "退步掌",
    cost: 0,
    type: "skill",
    text: "身后一格为空则后退，获得 5 点格挡。",
    flavor: "让出半步，掌还在。",
    block: 5,
  },
  split: {
    id: "split",
    name: "裂桩",
    cost: 1,
    type: "attack",
    text: "拆掉身前的桩。没有桩则造成 7 点伤害。",
    flavor: "桩是给人站的，不是给你挡的。",
    damage: 7,
  },
  close: {
    id: "close",
    name: "贴身",
    cost: 1,
    type: "skill",
    text: "移到对方身前。路要空。",
    flavor: "七步不够，就走成一步。",
  },
  elbow: {
    id: "elbow",
    name: "压肘",
    cost: 2,
    type: "attack",
    text: "造成 14 点伤害。",
    flavor: "肘比掌短，比刀近。",
    damage: 14,
  },
  sweep: {
    id: "sweep",
    name: "扫步",
    cost: 1,
    type: "attack",
    text: "击退 1 格。抽 1 张牌。",
    flavor: "脚先到，人后到。",
    knock: 1,
  },
  mend: {
    id: "mend",
    name: "吐纳",
    cost: 1,
    type: "skill",
    text: "回复 5 点生命。",
    flavor: "石台下还有一口气。",
    heal: 5,
  },
  mend2: {
    id: "mend2",
    name: "深息",
    cost: 1,
    type: "skill",
    text: "回复 8 点生命。",
    flavor: "气走完一圈。",
    heal: 8,
  },
  cut: {
    id: "cut",
    name: "斩",
    cost: 1,
    type: "attack",
    text: "造成 6 点。相邻再加 3 点。",
    flavor: "刀认的是胸口，不是风。",
    damage: 6,
    nearBonus: 3,
  },
  thrust: {
    id: "thrust",
    name: "戳",
    cost: 1,
    type: "attack",
    text: "造成 4 点。隔至少 2 格则 7 点。",
    flavor: "枪要有空，才伸得直。",
    damage: 4,
    farBonus: 3,
  },
  pierce: {
    id: "pierce",
    name: "刺",
    cost: 1,
    type: "attack",
    text: "造成 6 点，击退 1 格。",
    flavor: "剑走的是一线。人跟着退半步。",
    damage: 6,
    knock: 1,
  },
  plant: {
    id: "plant",
    name: "点地",
    cost: 1,
    type: "skill",
    text: "身前一格为空则落一根桩。",
    flavor: "棍先认步，再认人。",
    plant: true,
  },
  hookpull: {
    id: "hookpull",
    name: "钩挂",
    cost: 1,
    type: "attack",
    text: "把对方拉近 2 格，造成 3 点伤害。",
    flavor: "钩不推门。钩把门拉过来。",
    damage: 3,
    pullEnemy: 2,
  },
  bleedcut: {
    id: "bleedcut",
    name: "裂创",
    cost: 1,
    type: "attack",
    text: "造成 4 点伤害。敌人每回合再失 3 血，可叠。",
    flavor: "口子留着。血自己会走。",
    damage: 4,
    bleed: 3,
    school: "staff",
  },
  expose: {
    id: "expose",
    name: "破绽",
    cost: 1,
    type: "skill",
    text: "敌人下两下挨打 +4。对方出手 -3，两回合。抽 1。",
    flavor: "气先乱，招才乱。",
    expose: 2,
    frail: 2,
    school: "sword",
  },
  thorns: {
    id: "thorns",
    name: "反震",
    cost: 1,
    type: "skill",
    text: "获得 5 格挡。这回合挨打回敬 4。",
    flavor: "桩吃力，力还人。",
    block: 5,
    thorns: 4,
    school: "staff",
  },
  inbreath: {
    id: "inbreath",
    name: "纳息",
    cost: 1,
    type: "skill",
    text: "下回合劲力 +2。抽 1。",
    flavor: "这一口先压进丹田。",
  },
  combo: {
    id: "combo",
    name: "连手",
    cost: 0,
    type: "skill",
    text: "连势 +1。下一张攻击按连势各加 2 伤。",
    flavor: "第二掌认第一掌。",
    combo: true,
  },
  haste: {
    id: "haste",
    name: "抢先",
    cost: 1,
    type: "skill",
    text: "先机 +3。抽 1 张牌。",
    flavor: "手先到的人，招才认。",
    pace: 3,
  },
  haste2: {
    id: "haste2",
    name: "占先",
    cost: 1,
    type: "skill",
    text: "先机 +5。抽 1 张牌。",
    flavor: "这一拍从别人手里拿回来。",
    pace: 5,
  },
  follow: {
    id: "follow",
    name: "追掌",
    cost: 0,
    type: "attack",
    text: "本回合已出过攻击则打 6，否则 3。",
    flavor: "第二掌接第一掌的空。",
    damage: 6,
  },
  follow2: {
    id: "follow2",
    name: "追魂掌",
    cost: 0,
    type: "attack",
    text: "本回合已出过攻击则打 8，否则 4。",
    flavor: "空门开了，掌就进去。",
    damage: 8,
  },
  twinpalm: {
    id: "twinpalm",
    name: "双掌",
    cost: 1,
    type: "attack",
    text: "连打两掌，各 4 点。蓄劲只吃第一掌。",
    flavor: "左右开弓，门才认。",
    damage: 4,
  },
  brace: {
    id: "brace",
    name: "稳步",
    cost: 1,
    type: "skill",
    text: "获得 6 点格挡。抽 1。",
    flavor: "脚先站住，掌才有根。",
    block: 6,
  },
  chain: {
    id: "chain",
    name: "连环",
    cost: 1,
    type: "attack",
    text: "打 5。若有连势则打 9 并抽 1。",
    flavor: "一掌未收，二掌已到。",
    damage: 5,
  },
  chain2: {
    id: "chain2",
    name: "连环开山",
    cost: 1,
    type: "attack",
    text: "打 7。若有连势则打 11 并抽 1。",
    flavor: "连势叠到骨缝里。",
    damage: 7,
  },
  gather: {
    id: "gather",
    name: "聚气",
    cost: 1,
    type: "skill",
    text: "本场气脉 +1（最多 3）。抽 1。攻击各加气脉点。",
    flavor: "一口气压进小臂，这一场都认。",
    flow: 1,
  },
  gather2: {
    id: "gather2",
    name: "聚气入骨",
    cost: 1,
    type: "skill",
    text: "本场气脉 +2（最多 3）。抽 1。",
    flavor: "气沉到脚底板，掌才有根。",
    flow: 2,
  },
  setup: {
    id: "setup",
    name: "铺势",
    cost: 0,
    type: "skill",
    text: "铺势 +1。抽 1。收势掌认这层。",
    flavor: "先把门打开，掌再进去。",
    setupGain: 1,
  },
  finisher: {
    id: "finisher",
    name: "收势掌",
    cost: 1,
    type: "attack",
    text: "打 4。每层铺势再 +5，并清掉铺势。",
    flavor: "铺完了，这一掌才叫收。",
    damage: 4,
    finisher: true,
  },
  finisher2: {
    id: "finisher2",
    name: "收势开山",
    cost: 1,
    type: "attack",
    text: "打 6。每层铺势再 +6，并清掉铺势。",
    flavor: "铺势叠满，门就认这一掌。",
    damage: 6,
    finisher: true,
  },
  weave: {
    id: "weave",
    name: "搓手",
    cost: 1,
    type: "skill",
    text: "上一招是攻击则格挡 8 并连势 +1；否则蓄劲 +3。",
    flavor: "攻守一搓，才叫会走。",
    weave: true,
  },
  echo: {
    id: "echo",
    name: "尾劲",
    cost: 1,
    type: "skill",
    text: "下回第一掌伤害 +6。",
    flavor: "这一息没打完，劲还在腕子里。",
    echo: 6,
  },  ironform: {
    id: "ironform",
    name: "铁布",
    cost: 2,
    type: "skill",
    text: "格挡 10。之后两回开局各有 6 点格挡。",
    flavor: "布衫底下是肉，肉底下是气。",
    block: 10,
    retainTurns: 2,
    retainAmt: 6,
  },  marking: {
    id: "marking",
    name: "点穴",
    cost: 1,
    type: "attack",
    text: "打 4。点穴印 +2。本场攻击各加印记点。",
    flavor: "指尖落处，门就开一线。",
    damage: 4,
    mark: 2,
  },
  rift: {
    id: "rift",
    name: "开缝",
    cost: 1,
    type: "attack",
    text: "打 5。有印则吃 1 层再 +6 并抽 1。",
    flavor: "缝开了，掌就塞进去。",
    damage: 5,
  },
  mirror: {
    id: "mirror",
    name: "对招",
    cost: 1,
    type: "skill",
    text: "看他这一息要打多少，卸多少（最多 14）。",
    flavor: "他抬手，你已经卸在路上。",
    mirror: true,
  },
  layer: {
    id: "layer",
    name: "叠掌",
    cost: 1,
    type: "attack",
    text: "打 3。本回合已出过攻则再叠裂创 2、连势 +1。",
    flavor: "第一掌开门，第二掌才叠。",
    damage: 3,
    layer: true,
  },
  tide: {
    id: "tide",
    name: "潮劲",
    cost: 0,
    type: "skill",
    text: "下回劲力 +1。有气脉则抽 1。",
    flavor: "潮退了，下一拍还会回来。",
    tide: true,
    energyNext: 1,
  },
};

export const UPGRADES: Partial<Record<CardId, CardId>> = {
  strike: "strike2",
  defend: "defend2",
  push: "push2",
  charge: "charge2",
  advance: "advance2",
  mend: "mend2",
  haste: "haste2",
  follow: "follow2",
  chain: "chain2",
  gather: "gather2",
  finisher: "finisher2",
};

export const BASICS: CardId[] = [
  "strike",
  "defend",
  "push",
  "charge",
  "advance",
  "mend",
  "brace",
  "combo",
  "setup",
  "gather",
];
export const VERBS: CardId[] = [
  "drawcut",
  "backpalm",
  "split",
  "close",
  "elbow",
  "sweep",
  "cut",
  "thrust",
  "pierce",
  "plant",
  "hookpull",
  "bleedcut",
  "expose",
  "thorns",
  "inbreath",
  "combo",
  "haste",
  "follow",
  "twinpalm",
  "brace",
  "chain",
  "gather",
  "setup",
  "finisher",
  "weave",
  "echo",
  "ironform",
  "marking",
  "rift",
  "mirror",
  "layer",
  "tide",
];

export const STARTER_DECK: CardId[] = [
  "strike",
  "strike",
  "strike",
  "defend",
  "push",
  "charge",
  "advance",
  "advance",
  "mend",
  "defend",
  "setup",
  "gather",
  "combo",
  "finisher",
  "follow",
  "weave",
];

export const STARTER = {
  playerHp: BASE_HP,
  enemyHp: 56,
  enemyDamage: 18,
  playerPos: 0,
  enemyPos: 5,
  energy: 3,
  gold: 49,
  floor: 1,
};

export const HEROES: HeroDef[] = [
  {
    id: "rail",
    name: "轨刃",
    title: "破门刀",
    sect: "推宫一门",
    verb: "推、撞、占步",
    hp: "28",
    crime: "比武已判「推开」，你还是拔了真刀。江湖叫这作法外刃。",
    pitch: "码头上替人踹过不少门。比武已经判了推开，你还是把刀拔了。名册上那一笔墨，是从港律开始追的。",
    locked: false,
  },
  {
    id: "seer",
    name: "镜亭",
    title: "观气客",
    sect: "镜廷残谱",
    verb: "观气、破绽、连手",
    hp: "24",
    crime: "改过对方已经亮出的招。石台按旧招挨打，你按新招活下来。",
    pitch: "镜廷的人。观气，不观这一掌。名册上缺的那一笔，要从税卡对着镜子找回来。",
    locked: false,
  },
  {
    id: "sapper",
    name: "工兵",
    title: "桩师",
    sect: "垂街机关",
    verb: "落桩、占格、反震",
    hp: "32",
    crime: "在未亮的位置落下一根桩，挡掉一次合法冲锋。",
    pitch: "缆厂的桩还认你。巷里的步不认。你要把桩重新钉进这条官道。",
    locked: false,
  },
];

export const TECHNIQUES: Record<TechniqueId, TechniqueDef> = {
  longPush: {
    id: "longPush",
    name: "开山劲",
    text: "击退再多 1 格。",
    flavor: "门比人先开。",
    chapter: "dock",
  },
  backstep: {
    id: "backstep",
    name: "回身",
    text: "进步无路则后退。",
    flavor: "前脚不行，后脚还在。",
    chapter: "dock",
  },
  keepGuard: {
    id: "keepGuard",
    name: "残劲",
    text: "收势时留下 4 点格挡。",
    flavor: "力卸完，腕还硬。",
    chapter: "dock",
  },
  hardWall: {
    id: "hardWall",
    name: "震壁",
    text: "撞壁伤害至少 12 点。",
    flavor: "壁比门硬，人也比门硬。",
    chapter: "dock",
  },
  brightBlade: {
    id: "brightBlade",
    name: "亮刀残谱",
    text: "相邻时攻击伤害 +3。",
    flavor: "刀已经亮了，掌就不必藏。",
    chapter: "dock",
  },
  bodyCheck: {
    id: "bodyCheck",
    name: "对撞",
    text: "进步若撞上人，造成 6 点伤害。",
    flavor: "让开的那一步，改成撞。",
    chapter: "dock",
  },
  heelStake: {
    id: "heelStake",
    name: "后桩",
    text: "开场在第 2 步落一根桩。",
    flavor: "先把退的那一步钉上。",
    chapter: "dock",
  },
  shortCharge: {
    id: "shortCharge",
    name: "绊步",
    text: "对方冲锋少走 1 步。",
    flavor: "巷里迈不开第三步。",
    chapter: "alley",
  },
  ghostStep: {
    id: "ghostStep",
    name: "镜步",
    text: "进步可穿过桩。",
    flavor: "桩认人，不认影。",
    chapter: "alley",
  },
  trapWard: {
    id: "trapWard",
    name: "识机",
    text: "你不受机关格伤害。",
    flavor: "机簧响的时候，脚已经不在那儿。",
    chapter: "alley",
  },
  tether: {
    id: "tether",
    name: "纤力",
    text: "收势时若相隔超过 2 格，把对方拉近 1 格。",
    flavor: "缆还在手上。",
    chapter: "alley",
  },
  closeCut: {
    id: "closeCut",
    name: "巷刃",
    text: "抽刀始终按相邻结算。",
    flavor: "巷窄，刀不必出鞘。",
    chapter: "alley",
  },
  delayGuard: {
    id: "delayGuard",
    name: "等手",
    text: "对方蓄势时，你获得 3 点格挡。",
    flavor: "他要过一拍。你就卸这一拍。",
    chapter: "court",
  },
  throne: {
    id: "throne",
    name: "门墙",
    text: "你在第 1 步时，卸力类格挡 +4。",
    flavor: "背贴着门，力有地方去。",
    chapter: "court",
  },
  nightStep: {
    id: "nightStep",
    name: "夜步残谱",
    text: "开战先有 1 点格挡。",
    flavor: "井底下的人，先把气沉住。",
    chapter: "dock",
  },
  leftover: {
    id: "leftover",
    name: "余劲",
    text: "收势时留下 1 点劲力到下回合。",
    flavor: "这一拍没打完，下一拍还热。",    chapter: "dock",
  },
  rebound: {
    id: "rebound",
    name: "回桩",
    text: "你挨打时回敬 3 点。",
    flavor: "力打在桩上，桩还人。",
    chapter: "dock",
  },
  stackHand: {
    id: "stackHand",
    name: "多手",
    text: "手里多留一张。",
    flavor: "谱多一页，步就多一拍。",
    chapter: "dock",
  },
};

export const HEARTS: Record<HeartId, HeartDef> = {
  iron: {
    id: "iron",
    name: "铁布衫",
    text: "出门时生命 30。",
    flavor: "衣是旧的，骨是硬的。",
  },
  breath: {
    id: "breath",
    name: "调息",
    text: "赢下一场，多回 1 点。",
    flavor: "石台下还有一口气。",
  },
  empty: {
    id: "empty",
    name: "空门",
    text: "不调息，不穿衫。",
    flavor: "身上只剩残谱。",
  },
};

export const ENEMIES: Record<EnemyId, EnemyDef> = {
  catcher: {
    id: "catcher",
    name: "赵捕",
    title: "码头官差",
    hp: 56,
    pos: 5,
    skill: "亮刀",
    pitch: "「刀在这儿。名册上没有你。」",
    remnant: "brightBlade",
    pattern: [{ kind: "strike", damage: 18 }],
  },
  escort: {
    id: "escort",
    name: "沈镖",
    title: "走水护镖",
    hp: 72,
    pos: 3,
    skill: "冲锋",
    pitch: "「让开。这箱不是给你看的。」",
    remnant: "bodyCheck",
    pattern: [{ kind: "charge", damage: 18, steps: 3 }],
  },
  piler: {
    id: "piler",
    name: "桩阿大",
    title: "垂街残徒",
    hp: 74,
    pos: 4,
    skill: "落桩",
    pitch: "「先下桩。船今晚不接除名。」",
    remnant: "heelStake",
    pattern: [{ kind: "stake" }, { kind: "strike", damage: 19 }],
  },
  hauler: {
    id: "hauler",
    name: "纤佬",
    title: "岸缆",
    hp: 72,
    pos: 4,
    skill: "拉",
    pitch: "「缆在我手里。巷里的人叫我拦住往北的。」",
    remnant: "tether",
    pattern: [{ kind: "pull", steps: 2 }, { kind: "strike", damage: 18 }],
  },
  alley: {
    id: "alley",
    name: "巷刃",
    title: "垂街夜行",
    hp: 70,
    pos: 3,
    skill: "抢步",
    pitch: "「问半页纸的人，巷里只有一步。」",
    remnant: "closeCut",
    pattern: [{ kind: "lunge", damage: 18 }],
  },
  trapper: {
    id: "trapper",
    name: "簧二",
    title: "簧片",
    hp: 70,
    pos: 4,
    skill: "下机",
    pitch: "「北栅是镜廷的。脚底下。」",
    remnant: "trapWard",
    pattern: [{ kind: "trap" }, { kind: "strike", damage: 18 }],
  },
  delay: {
    id: "delay",
    name: "迟手裴",
    title: "镜廷过客",
    hp: 78,
    pos: 4,
    skill: "蓄势",
    pitch: "「这一拍让给你。名册要写得干净。」",
    remnant: "delayGuard",
    pattern: [{ kind: "windup" }, { kind: "strike", damage: 26 }],
  },
  twin: {
    id: "twin",
    name: "影步",
    title: "镜中人",
    hp: 72,
    pos: 3,
    skill: "换位",
    pitch: "「你站的是我的位置。名册盖住你的时候，留下了我。」",
    remnant: "ghostStep",
    pattern: [{ kind: "swap" }, { kind: "strike", damage: 19 }],
  },
  lord: {
    id: "lord",
    name: "门墙顾",
    title: "门墙",
    hp: 88,
    pos: 4,
    skill: "冲、桩、劈",
    pitch: "「名册在门里。墨还没干。」",
    remnant: "throne",
    pattern: [
      { kind: "charge", damage: 17, steps: 2 },
      { kind: "stake" },
      { kind: "strike", damage: 22 },
    ],
  },
  bandit: {
    id: "bandit",
    name: "岗花子",
    title: "院外蹲手",
    hp: 74,
    pos: 4,
    skill: "冲劈",
    pitch: "「过帖的人身上有油水。」",
    remnant: "hardWall",
    pattern: [{ kind: "charge", damage: 17, steps: 2 }, { kind: "strike", damage: 19 }],
  },
  raider: {
    id: "raider",
    name: "潮口",
    title: "潮口",
    hp: 76,
    pos: 4,
    skill: "拉缆",
    pitch: "「岸上的货，潮里也认。」",
    remnant: "longPush",
    pattern: [{ kind: "pull", steps: 2 }, { kind: "strike", damage: 19 }],
  },
  robber: {
    id: "robber",
    name: "缆刀",
    title: "缆厂夜手",
    hp: 68,
    pos: 3,
    skill: "抢步",
    pitch: "「契不在身上，刀也认。」",
    remnant: "shortCharge",
    pattern: [{ kind: "lunge", damage: 18 }],
  },
  smuggler: {
    id: "smuggler",
    name: "换口盐",
    title: "换口的人",
    hp: 72,
    pos: 4,
    skill: "卸力",
    pitch: "「官盐朝西。我朝东。」",
    remnant: "keepGuard",
    pattern: [{ kind: "guard", block: 12 }, { kind: "windup" }, { kind: "strike", damage: 20 }],
  },
  thug: {
    id: "thug",
    name: "巷霸",
    title: "巷口",
    hp: 68,
    pos: 3,
    skill: "回身",
    pitch: "「往北的人，把口袋留下。」",
    remnant: "backstep",
    pattern: [{ kind: "strike", damage: 17 }, { kind: "charge", damage: 16, steps: 2 }],
  },
  intruder: {
    id: "intruder",
    name: "夜客",
    title: "破门的人",
    hp: 42,
    pos: 4,
    skill: "劈",
    pitch: "「屋里那人，帖还没递。」",
    remnant: "backstep",
    pattern: [{ kind: "strike", damage: 13 }],
  },
  brute: {
    id: "brute",
    name: "坡蹲",
    title: "坡上蹲手",
    hp: 76,
    pos: 4,
    skill: "撞岗",
    pitch: "「岗是我的。人留下。」",
    remnant: "bodyCheck",
    pattern: [{ kind: "charge", damage: 17, steps: 2 }, { kind: "strike", damage: 19 }],
  },
  cavehand: {
    id: "cavehand",
    name: "缝手",
    title: "潮缝",
    hp: 74,
    pos: 3,
    skill: "拖",
    pitch: "「缝里的人，不认名册。」",
    remnant: "tether",
    pattern: [{ kind: "pull", steps: 2 }, { kind: "lunge", damage: 18 }],
  },
  warden: {
    id: "warden",
    name: "岗老",
    title: "岗门",
    hp: 80,
    pos: 4,
    skill: "蓄势",
    pitch: "「过岗要留下一刀。」",
    remnant: "delayGuard",
    pattern: [{ kind: "windup" }, { kind: "strike", damage: 26 }],
  },
  inkhand: {
    id: "inkhand",
    name: "墨手",
    title: "税卡夜笔",
    hp: 44,
    pos: 4,
    skill: "点墨",
    pitch: "「案下那一笔，还没干。」",
    remnant: "leftover",
    pattern: [{ kind: "strike", damage: 13 }],
  },
  bookcut: {
    id: "bookcut",
    name: "裁页",
    title: "潮祠刀笔",
    hp: 72,
    pos: 4,
    skill: "抽刀",
    pitch: "「页裁过。名就短一截。」",
    remnant: "stackHand",
    pattern: [{ kind: "lunge", damage: 17 }, { kind: "strike", damage: 16 }],
  },
  nametaker: {
    id: "nametaker",
    name: "夺名吏",
    title: "岗上收名",
    hp: 82,
    pos: 4,
    skill: "蓄势",
    pitch: "「名留下。人可以走。」",
    remnant: "leftover",
    pattern: [{ kind: "windup" }, { kind: "strike", damage: 26 }],
  },
  glasspin: {
    id: "glasspin",
    name: "镜钉",
    title: "潮口抽钉",
    hp: 74,
    pos: 4,
    skill: "拉",
    pitch: "「镜子里的钉子，要拔出来。」",
    remnant: "rebound",
    pattern: [{ kind: "pull", steps: 2 }, { kind: "strike", damage: 18 }],
  },
  knotboss: {
    id: "knotboss",
    name: "死结手",
    title: "坞里那结",
    hp: 76,
    pos: 4,
    skill: "拉缆",
    pitch: "「结是死的。人不是。」",
    remnant: "leftover",
    pattern: [{ kind: "pull", steps: 2 }, { kind: "lunge", damage: 17 }],
  },
  stakeboss: {
    id: "stakeboss",
    name: "钉桩的",
    title: "缆厂桩师",
    hp: 48,
    pos: 4,
    skill: "落桩",
    pitch: "「这根桩是我钉的。你把它拔了。」",
    remnant: "rebound",
    pattern: [{ kind: "stake" }, { kind: "strike", damage: 14 }],
  },
  tutorPace: {
    id: "tutorPace",
    name: "步阿宽",
    title: "岗棚教习",
    hp: 30,
    pos: 4,
    skill: "让步",
    pitch: "“步是让出来的。你站在我要踩的地方，就是自己找撞。”",
    remnant: "leftover",
    pattern: [{ kind: "charge", damage: 10, steps: 2 }],
  },
  tutorWard: {
    id: "tutorWard",
    name: "掌阿稳",
    title: "岸上教习",
    hp: 32,
    pos: 4,
    skill: "卸力",
    pitch: "“掌打在卸上，力才回去。硬接会倒。”",
    remnant: "leftover",
    pattern: [{ kind: "strike", damage: 11 }],
  },
  tutorEdge: {
    id: "tutorEdge",
    name: "谱阿正",
    title: "巷口教习",
    hp: 30,
    pos: 4,
    skill: "分谱",
    pitch: "“拳谱是拳谱。刀谱是刀谱。别混着使。”",
    remnant: "leftover",
    pattern: [{ kind: "strike", damage: 10 }],
  },
};

export const SPAR_ENEMIES: EnemyId[] = ["tutorPace", "tutorWard", "tutorEdge"];

export function isSparEnemy(id: EnemyId): boolean {
  return SPAR_ENEMIES.includes(id);
}

export const ENEMY_PACE: Partial<Record<EnemyId, number>> = {
  catcher: 4,
  escort: 5,
  piler: 3,
  delay: 2,
  trapper: 8,
  alley: 6,
  twin: 8,
  glasspin: 8,
  robber: 6,
  thug: 6,
  stakeboss: 4,
  hauler: 5,
  bandit: 5,
  raider: 5,
  brute: 5,
  cavehand: 6,
  bookcut: 6,
  knotboss: 5,
  lord: 4,
  smuggler: 4,
  warden: 3,
  nametaker: 3,
  inkhand: 5,
  intruder: 5,
};

export function enemyPace(id: EnemyId): number {
  return ENEMY_PACE[id] ?? 5;
}

export const CHAPTER_TECH: Record<ChapterId, TechniqueId[]> = {
  dock: ["longPush", "backstep", "keepGuard", "hardWall", "leftover", "rebound", "stackHand"],
  alley: ["shortCharge", "ghostStep", "trapWard"],
  court: ["delayGuard", "throne"],
};

export const CHALLENGE: EnemyId[] = [
  "bandit",
  "raider",
  "robber",
  "smuggler",
  "thug",
  "brute",
  "cavehand",
  "warden",
];

export const CHAPTERS: Record<
  ChapterId,
  { name: string; kicker: string; next: ChapterId | null; index: number }
> = {
  dock: { name: "码头", kicker: "港律", next: "alley", index: 1 },
  alley: { name: "垂街", kicker: "巷律", next: "court", index: 2 },
  court: { name: "镜廷", kicker: "门律", next: null, index: 3 },
};

export function intentLabel(intent: Intent): string {
  if (intent.kind === "strike") return `攻击 ${intent.damage}`;
  if (intent.kind === "charge") return `冲锋 ${intent.steps} 步 · ${intent.damage}`;
  if (intent.kind === "stake") return "落桩";
  if (intent.kind === "pull") return `拉 ${intent.steps} 步`;
  if (intent.kind === "trap") return "下机";
  if (intent.kind === "windup") return "蓄势";
  if (intent.kind === "lunge") return `抢步 ${intent.damage}`;
  return "换位";
}

export function intentMark(intent: Intent): string {
  if (intent.kind === "strike") return String(intent.damage);
  if (intent.kind === "charge") return String(intent.damage);
  if (intent.kind === "lunge") return String(intent.damage);
  if (intent.kind === "pull") return "拉";
  if (intent.kind === "trap") return "机";
  if (intent.kind === "windup") return "蓄";
  if (intent.kind === "swap") return "换";
  return "桩";
}

export const WORLD = {
  title: "明手",
  kicker: "港律 · 垂街 · 镜廷",
  lead: "江湖不许暗手。官道上的城把比武收成一条死规矩：出招必先亮招。偷袭的人，名册上除名。",
  you: "三人共用一张港图。出生不同，名册上的墨就不同。刀、镜、桩，各追各的那一笔。",
};

export function heartHp(id: HeartId): number {
  return id === "iron" ? 30 : BASE_HP;
}

export function winHeal(id: HeartId): number {
  return id === "breath" ? 4 : 3;
}
