import type {
  CardDef,
  CardId,
  ChapterId,
  EnemyDef,
  EnemyId,
  HeartDef,
  HeartId,
  HeroDef,
  Intent,
  TechniqueDef,
  TechniqueId,
  WeaponId,
} from "./types";
import { BASE_HP } from "./types";
import { GENERATED_ELITE_ENERGY, GENERATED_ENEMIES, GENERATED_ENEMY_WEAPON } from "./foeCatalog";
import { ROGUE_CARD_DEFS } from "./rogueCards";
import { SIGNATURE_BREAK } from "./enemySignatures";

export const CARDS: Record<CardId, CardDef> = {
  strike: {
    id: "strike",
    name: "劈掌",
    cost: 1,
    type: "attack",
    text: "造成 5 点伤害。",
    flavor: "推宫一门的见面礼。",
    damage: 5,
  },
  defend: {
    id: "defend",
    name: "卸力",
    cost: 1,
    type: "skill",
    text: "获得 8 点格挡。",
    flavor: "力从脚走。",
    block: 8,
  },
  push: {
    id: "push",
    name: "推宫",
    cost: 2,
    type: "attack",
    text: "击退 2 格。撞壁再受 8 点伤害。",
    flavor: "破门不问门闩。",
    knock: 2,
    wall: 8,
  },
  charge: {
    id: "charge",
    name: "蓄劲",
    cost: 1,
    type: "skill",
    text: "下一张攻击伤害 +4。势 +1。",
    flavor: "一口气先压进小腹。",
    chargeBonus: 4,
  },
  advance: {
    id: "advance",
    name: "进步",
    cost: 1,
    type: "skill",
    text: "身前一格为空则前进，抽 1 张牌。",
    flavor: "七步之内。",
    steps: 1,
  },
  strike2: {
    id: "strike2",
    name: "开山掌",
    cost: 2,
    type: "attack",
    text: "造成 10 点伤害并击退 1。",
    flavor: "掌风比刀快半寸，人要让开。",
    damage: 10,
    knock: 1,
  },
  defend2: {
    id: "defend2",
    name: "卸力入骨",
    cost: 1,
    type: "skill",
    text: "获得 12 点格挡，抽 1。",
    flavor: "力走进骨缝里，手还能再摸一张。",
    block: 12,
  },
  push2: {
    id: "push2",
    name: "破门",
    cost: 3,
    type: "attack",
    text: "击退 3 格。撞壁再受 10 点伤害。",
    flavor: "门闩先走。",
    knock: 3,
    wall: 10,
  },
  charge2: {
    id: "charge2",
    name: "沉劲",
    cost: 3,
    type: "skill",
    text: "下一张攻击伤害 +7。",
    flavor: "气沉到脚底板。",
    chargeBonus: 7,
  },
  advance2: {
    id: "advance2",
    name: "纵步",
    cost: 1,
    type: "skill",
    text: "身前最多前进 2 格。抽 1 张牌。",
    flavor: "两步并作一步。",
    steps: 2,
  },
  drawcut: {
    id: "drawcut",
    name: "抽刀",
    cost: 1,
    type: "attack",
    text: "相邻打 8 并叠 1 裂创，否则 4。",
    flavor: "刀还在鞘里时，人已经到了。",
    damage: 4,
  },
  backpalm: {
    id: "backpalm",
    name: "退步掌",
    cost: 0,
    type: "skill",
    text: "身后一格为空则后退，获得 5 点格挡。",
    flavor: "让出半步，掌还在。",
    block: 5,
  },
  split: {
    id: "split",
    name: "裂桩",
    cost: 1,
    type: "attack",
    text: "拆掉身前的桩。没有桩则造成 7 点伤害。",
    flavor: "桩是给人站的，不是给你挡的。",
    damage: 7,
  },
  close: {
    id: "close",
    name: "贴身",
    cost: 1,
    type: "skill",
    text: "移到对方身前。路要空。",
    flavor: "七步不够，就走成一步。",
  },
  elbow: {
    id: "elbow",
    name: "压肘",
    cost: 3,
    type: "attack",
    text: "造成 15 点伤害。",
    flavor: "肘比掌短，比刀近。",
    damage: 15,
  },
  sweep: {
    id: "sweep",
    name: "扫步",
    cost: 1,
    type: "attack",
    text: "击退 1 格。抽 1 张牌。",
    flavor: "脚先到，人后到。",
    knock: 1,
  },
  mend: {
    id: "mend",
    name: "吐纳",
    cost: 1,
    type: "skill",
    text: "回复 5 点生命。",
    flavor: "石台下还有一口气。",
    heal: 5,
  },
  mend2: {
    id: "mend2",
    name: "深息",
    cost: 1,
    type: "skill",
    text: "回复 8 点生命，并清裂创。",
    flavor: "气走完一圈，创口也收口。",
    heal: 8,
    clearBleed: true,
  },
  cut: {
    id: "cut",
    name: "斩",
    cost: 2,
    type: "attack",
    text: "贴身 10，叠 2 裂创。距 2 则 4。",
    flavor: "刀认的是胸口，不是风。",
    damage: 9,
    nearBonus: 3,
    bleed: 2,
  },
  thrust: {
    id: "thrust",
    name: "戳",
    cost: 1,
    type: "attack",
    text: "造成 3 点。隔 2 格则 5，更远 8。贴身打不出。",
    flavor: "枪要有空，才伸得直。",
    damage: 4,
    farBonus: 3,
  },
  pierce: {
    id: "pierce",
    name: "刺",
    cost: 1,
    type: "attack",
    text: "造成 6 点，击退 1 格。",
    flavor: "剑走的是一线。人跟着退半步。",
    damage: 6,
    knock: 1,
  },
  plant: {
    id: "plant",
    name: "点地",
    cost: 1,
    type: "skill",
    text: "身前一格为空则落一根桩。",
    flavor: "棍先认步，再认人。",
    plant: true,
  },
  hookpull: {
    id: "hookpull",
    name: "钩挂",
    cost: 1,
    type: "attack",
    text: "把对方拉近 2 格，造成 3 点伤害。",
    flavor: "钩不推门。钩把门拉过来。",
    damage: 3,
    pullEnemy: 2,
  },
  bleedcut: {
    id: "bleedcut",
    name: "裂创",
    cost: 1,
    type: "attack",
    text: "造成 4 点伤害。敌人每回合再失 3 血，可叠。",
    flavor: "口子留着。血自己会走。",
    damage: 4,
    bleed: 3,
    school: "staff",
  },
  expose: {
    id: "expose",
    name: "破绽",
    cost: 1,
    type: "skill",
    text: "敌人下两下 +4。他出手 -3，两回。抽 1。",
    flavor: "气先乱，招才乱。",
    expose: 2,
    frail: 2,
    school: "sword",
  },
  thorns: {
    id: "thorns",
    name: "反震",
    cost: 1,
    type: "skill",
    text: "获得 5 格挡。这回合挨打回敬 4。",
    flavor: "桩吃力，力还人。",
    block: 5,
    thorns: 4,
    school: "staff",
  },
  inbreath: {
    id: "inbreath",
    name: "纳息",
    cost: 1,
    type: "skill",
    text: "下回合劲力 +2。抽 1。",
    flavor: "这一口先压进丹田。",
  },
  combo: {
    id: "combo",
    name: "连手",
    cost: 1,
    stackTaxQi: 1,
    stackTaxHp: 1,
    type: "skill",
    text: "连势 +1。下一张攻击按连势各加 2 伤。",
    flavor: "第二掌认第一掌。",
    combo: true,
  },
  haste: {
    id: "haste",
    name: "抢先",
    cost: 1,
    type: "skill",
    text: "先机 +3。抽 1 张牌。",
    flavor: "手先到的人，招才认。",
    pace: 3,
  },
  haste2: {
    id: "haste2",
    name: "占先",
    cost: 1,
    type: "skill",
    text: "先机 +5。抽 1 张牌。",
    flavor: "这一拍从别人手里拿回来。",
    pace: 5,
  },
  follow: {
    id: "follow",
    name: "追掌",
    cost: 1,
    type: "attack",
    text: "本回合已出过攻击则打 6，否则 3。",
    flavor: "第二掌接第一掌的空。",
    damage: 6,
  },
  follow2: {
    id: "follow2",
    name: "追魂掌",
    cost: 2,
    type: "attack",
    text: "本回合已出过攻击则打 8，否则 4。",
    flavor: "空门开了，掌就进去。",
    damage: 8,
  },
  twinpalm: {
    id: "twinpalm",
    name: "双掌",
    cost: 2,
    type: "attack",
    text: "连打两掌，各 4 点。蓄劲只吃第一掌。",
    flavor: "左右开弓，门才认。",
    damage: 4,
  },
  brace: {
    id: "brace",
    name: "稳步",
    cost: 1,
    type: "skill",
    text: "获得 6 点格挡。抽 1。",
    flavor: "脚先站住，掌才有根。",
    block: 6,
  },
  chain: {
    id: "chain",
    name: "连环",
    cost: 2,
    type: "attack",
    text: "打 5。若有连势则打 9 并抽 1。",
    flavor: "一掌未收，二掌已到。",
    damage: 5,
  },
  chain2: {
    id: "chain2",
    name: "连环开山",
    cost: 3,
    type: "attack",
    text: "打 7。若有连势则打 11 并抽 1。",
    flavor: "连势叠到骨缝里。",
    damage: 7,
  },
  gather: {
    id: "gather",
    name: "聚气",
    cost: 1,
    type: "skill",
    text: "气脉 +1（最多 3）。抽 1。攻击加气脉。",
    flavor: "一口气压进小臂，这一场都认。",
    flow: 1,
  },
  gather2: {
    id: "gather2",
    name: "聚气入骨",
    cost: 2,
    type: "skill",
    text: "本场气脉 +2（最多 3）。抽 1。",
    flavor: "气沉到脚底板，掌才有根。",
    flow: 2,
  },
  setup: {
    id: "setup",
    name: "铺势",
    cost: 1,
    type: "skill",
    text: "铺势 +1。抽 1。收势掌认这层。",
    flavor: "先把门打开，掌再进去。",
    setupGain: 1,
  },
  finisher: {
    id: "finisher",
    name: "收势掌",
    cost: 2,
    setupCost: 1,
    type: "attack",
    text: "需铺势≥1。打 4，每层铺势再 +5，然后清掉铺势。",
    flavor: "铺完了，这一掌才叫收。",
    damage: 4,
    finisher: true,
  },
  finisher2: {
    id: "finisher2",
    name: "收势开山",
    cost: 4,
    type: "attack",
    text: "打 6。每层铺势再 +6，并清掉铺势。",
    flavor: "铺势叠满，门就认这一掌。",
    damage: 6,
    finisher: true,
  },
  weave: {
    id: "weave",
    name: "搓手",
    cost: 0,
    type: "skill",
    text: "上一招是攻则挡 8 并连势 +1；否则蓄劲 +3。本回合下一张牌耗劲 -1。",
    flavor: "攻守一搓，才叫会走。",
    weave: true,
    costDiscountNext: 1,
  },
  echo: {
    id: "echo",
    name: "尾劲",
    cost: 2,
    type: "skill",
    text: "下回第一掌伤害 +6。",
    flavor: "这一息没打完，劲还在腕子里。",
    echo: 6,
  },
  ironform: {
    id: "ironform",
    name: "铁布",
    cost: 2,
    type: "skill",
    text: "格挡 10。之后两回开局各有 6 点格挡。",
    flavor: "布衫底下是肉，肉底下是气。",
    block: 10,
    retainTurns: 2,
    retainAmt: 6,
  },
  marking: {
    id: "marking",
    name: "点穴",
    cost: 1,
    type: "attack",
    text: "打 4。点穴印 +2。本场攻击各加印记点。",
    flavor: "指尖落处，门就开一线。",
    damage: 4,
    mark: 2,
  },
  rift: {
    id: "rift",
    name: "开缝",
    cost: 1,
    type: "attack",
    text: "打 5。有印则吃 1 层再 +6 并抽 1。",
    flavor: "缝开了，掌就塞进去。",
    damage: 5,
  },
  mirror: {
    id: "mirror",
    name: "对招",
    cost: 1,
    type: "skill",
    text: "看他这一息要打多少，卸多少（最多 14）。",
    flavor: "他抬手，你已经卸在路上。",
    mirror: true,
  },
  layer: {
    id: "layer",
    name: "叠掌",
    cost: 2,
    type: "attack",
    text: "打 3。本息已出攻则叠裂创 2、连势 +1。",
    flavor: "第一掌开门，第二掌才叠。",
    damage: 3,
    layer: true,
  },
  tide: {
    id: "tide",
    name: "潮劲",
    cost: 3,
    type: "skill",
    text: "下回劲力 +1。有气脉则抽 1。",
    flavor: "潮退了，下一拍还会回来。",
    tide: true,
    energyNext: 1,
  },
  burySlash: {
    id: "burySlash",
    name: "埋刀",
    cost: 1,
    type: "skill",
    text: "埋反击（按气血撑数回）。挨打时回敬 7。",
    flavor: "刀先搁在袖里。他动手，才抽。",
    riposte: "slash",
  },
  buryBleed: {
    id: "buryBleed",
    name: "埋创",
    cost: 1,
    type: "skill",
    text: "埋反击（按气血撑数回）。挨打时叠 3 裂创。",
    flavor: "创口不是这一掌开的，是他撞上来的。",
    riposte: "bleed",
  },
  buryKnock: {
    id: "buryKnock",
    name: "埋步",
    cost: 1,
    type: "skill",
    text: "埋反击（按气血撑数回）。挨打时击退 1。",
    flavor: "脚先站死。他来了，路就让给他。",
    riposte: "knock",
  },
  buryWard: {
    id: "buryWard",
    name: "埋架",
    cost: 1,
    type: "skill",
    text: "埋反击（按气血撑数回）。挨打时挡 8 并回敬 4。",
    flavor: "架不是卸，是等他送手。",
    riposte: "ward",
  },
  salve: {
    id: "salve",
    name: "金创",
    cost: 1,
    type: "skill",
    text: "回 6。清掉你身上的裂创。",
    flavor: "布一裹，血先止。",
    heal: 6,
    clearBleed: true,
  },
  unbind: {
    id: "unbind",
    name: "通脉",
    cost: 1,
    type: "skill",
    text: "清掉封脉和滞步。抽 1。",
    flavor: "气走错了路，把它拽回来。",
    clearSeal: true,
  },
  sidestep: {
    id: "sidestep",
    name: "换位",
    cost: 1,
    type: "skill",
    text: "相邻对调。先机够则抽 1，否则乱步 1。",
    flavor: "你站的是他的步。墙也就换了边。",
    swap: true,
  },
  retreat: {
    id: "retreat",
    name: "撤步",
    cost: 0,
    type: "skill",
    text: "身后最多退 2 格。",
    flavor: "留得步在，不怕招老。",
  },
  suture: {
    id: "suture",
    name: "缝创",
    cost: 1,
    type: "skill",
    text: "4 回每回回 2。每两回裂创 -1。",
    flavor: "线比刀慢，可它不松开。",
    regen: 2,
    regenTurns: 4,
  },
  cauterize: {
    id: "cauterize",
    name: "烙口",
    cost: 0,
    type: "skill",
    text: "自损 4（留 1）。清裂创与封脉。",
    flavor: "肉是自己的。口子也是。",
    payHp: 4,
    clearBleed: true,
    clearSeal: true,
  },
  bindwound: {
    id: "bindwound",
    name: "收创",
    cost: 1,
    type: "skill",
    text: "有铺势吃 1 层：回 7 清裂创；否则回 2。",
    flavor: "铺完了不收掌，先收血。",
    heal: 2,
  },
  qiPulse: {
    id: "qiPulse",
    name: "脉息",
    cost: 1,
    type: "skill",
    text: "本场回劲 +1。抽 1。",
    flavor: "气走得匀，下一息才够用。",
    qiRegenSelf: 1,
    school: "any",
  },
  qiFlood: {
    id: "qiFlood",
    name: "灌劲",
    cost: 2,
    type: "skill",
    text: "立刻回 4 劲（不超过上限）。",
    flavor: "一口气灌满丹田。",
    energyNext: 4,
    school: "any",
  },
  palmSeal: {
    id: "palmSeal",
    name: "封门掌印",
    cost: 2,
    type: "attack",
    text: "伤 5。给敌禁技 1 息。",
    flavor: "掌印盖在脉口上。",
    damage: 5,
    foeMute: 1,
    school: "palm",
  },
  saberBleed: {
    id: "saberBleed",
    name: "拖刀创",
    cost: 2,
    type: "attack",
    text: "贴身伤 7，距 2 伤 4。裂创 +2。",
    flavor: "刀口不求一刀断，求他滴下去。",
    damage: 7,
    bleed: 2,
    school: "saber",
  },
  spearLock: {
    id: "spearLock",
    name: "锁步点",
    cost: 2,
    type: "attack",
    text: "伤 6。破绽 +2。滞手 1。",
    flavor: "枪尖点在他脚腕筋上。",
    damage: 6,
    expose: 2,
    frail: 1,
    school: "spear",
  },
  swordMute: {
    id: "swordMute",
    name: "封喉刺",
    cost: 2,
    type: "attack",
    text: "伤 5。裂创 +2。禁敌技 2 息。",
    flavor: "剑气压着他嗓子眼。",
    damage: 5,
    bleed: 2,
    foeMute: 2,
    school: "sword",
  },
  staffBind: {
    id: "staffBind",
    name: "缠棍",
    cost: 2,
    type: "skill",
    text: "格挡 8。敌手牌上限 -1（1 息）。缠压眩晕 1 段。",
    flavor: "棍影一圈，他袖里少一张。",
    block: 8,
    foeHandTax: 1,
    foeStun: 1,
    school: "staff",
  },
  hookDisarm: {
    id: "hookDisarm",
    name: "摘兵钩",
    cost: 2,
    type: "attack",
    text: "拉近 1。伤 4。缴械 2 息（敌攻击减半）。",
    flavor: "钩子先摘他手里那口刀。",
    pullEnemy: 1,
    damage: 4,
    foeDisarm: 2,
    school: "hook",
  },
  venomFog: {
    id: "venomFog",
    name: "毒雾",
    cost: 2,
    type: "skill",
    text: "敌裂创 +3。你也裂创 +1。",
    flavor: "风往两边吹。",
    bleed: 3,
    school: "any",
  },
  skillLock: {
    id: "skillLock",
    name: "禁招符",
    cost: 2,
    type: "skill",
    text: "敌禁技 2 息。",
    flavor: "符纸贴在他招式名上。",
    foeMute: 2,
    school: "any",
  },
  pouchSeal: {
    id: "pouchSeal",
    name: "封囊",
    cost: 1,
    type: "skill",
    text: "敌禁药/暗器 2 息。",
    flavor: "绳结一勒，腰袋打不开。",
    foeNoBag: 2,
    school: "any",
  },
  handCut: {
    id: "handCut",
    name: "削谱",
    cost: 2,
    type: "skill",
    text: "敌手牌上限 -1，持续 2 息。",
    flavor: "他袖里少一张能亮的。",
    foeHandTax: 2,
    school: "any",
  },
  qiLeech: {
    id: "qiLeech",
    name: "吸劲",
    cost: 2,
    type: "skill",
    text: "敌每回少回 1 劲，持续 2 息。你回劲 +1（本场）。",
    flavor: "他的气，借你一用。",
    foeQiBurn: 2,
    qiRegenSelf: 1,
    school: "any",
  },
  ironPulse: {
    id: "ironPulse",
    name: "铁脉",
    cost: 2,
    type: "skill",
    text: "格挡 6。本场回劲 +1。",
    flavor: "脉里走的是铁，不是慌。",
    block: 6,
    qiRegenSelf: 1,
    school: "any",
  },
  comboTax: {
    id: "comboTax",
    name: "忍手",
    cost: 1,
    type: "skill",
    text: "付 2 血叠 1 连势。抽 1。",
    flavor: "连势不是白来的。",
    stackTaxHp: 2,
    school: "any",
  },
  comboPay: {
    id: "comboPay",
    name: "兑现连势",
    cost: 2,
    type: "attack",
    text: "消耗 1 连势：伤 10。",
    flavor: "攒够了才敢拍出去。",
    damage: 10,
    comboCost: 1,
    school: "any",
  },
  setupTax: {
    id: "setupTax",
    name: "稳铺",
    cost: 2,
    stackTaxQi: 1,
    type: "skill",
    text: "铺势 +1。抽 1。额外耗 1 劲。",
    flavor: "铺得稳，收得响。",
    setupGain: 1,
    school: "any",
  },
  flowTax: {
    id: "flowTax",
    name: "沉脉",
    cost: 2,
    stackTaxQi: 1,
    type: "skill",
    text: "气脉 +1（上限 3）。额外耗 1 劲。",
    flavor: "气沉下去才算你的。",
    flow: 1,
    school: "any",
  },
  midStrike: {
    id: "midStrike",
    name: "中盘贯手",
    cost: 2,
    type: "attack",
    text: "伤 8。",
    flavor: "驿路上练出来的。",
    damage: 8,
    school: "any",
  },
  midGuard: {
    id: "midGuard",
    name: "中盘卸",
    cost: 2,
    type: "skill",
    text: "格挡 11。",
    flavor: "城门洞里的卸法。",
    block: 11,
    school: "any",
  },
  midPush: {
    id: "midPush",
    name: "中盘推",
    cost: 2,
    type: "attack",
    text: "击退 2。撞壁 9。",
    flavor: "官道上不讲情面。",
    knock: 2,
    wall: 9,
    school: "any",
  },
  lateAnvil: {
    id: "lateAnvil",
    name: "镇殿锤",
    cost: 4,
    type: "attack",
    text: "伤 16。",
    flavor: "大殿石砖都要让一让。",
    damage: 16,
    school: "any",
  },
  lateTide: {
    id: "lateTide",
    name: "潮涌",
    cost: 3,
    type: "skill",
    text: "气脉拉满。抽 2。",
    flavor: "后期的气，像江。",
    flow: 3,
    school: "any",
  },
  lateMirror: {
    id: "lateMirror",
    name: "镜反",
    cost: 3,
    type: "skill",
    text: "格挡 10。反震 +4。",
    flavor: "宫墙照人，也照刀。",
    block: 10,
    thorns: 4,
    school: "any",
  },
  lateChain: {
    id: "lateChain",
    name: "九连环",
    cost: 3,
    comboCost: 2,
    type: "attack",
    text: "耗 2 连势：伤 16 并抽 1。",
    flavor: "连势兑成雷。",
    damage: 16,
    school: "any",
  },
  lateWard: {
    id: "lateWard",
    name: "金汤",
    cost: 3,
    type: "skill",
    text: "格挡 16。铁布 4/1。",
    flavor: "城再大，也先护住胸口。",
    block: 16,
    retainAmt: 4,
    retainTurns: 1,
    school: "any",
  },
  lateBleed: {
    id: "lateBleed",
    name: "血河",
    cost: 3,
    type: "attack",
    text: "伤 7。裂创 +4。",
    flavor: "一刀开河。",
    damage: 7,
    bleed: 4,
    school: "any",
  },
  lateMute: {
    id: "lateMute",
    name: "哑阵",
    cost: 3,
    type: "skill",
    text: "敌禁技 3 息。",
    flavor: "阵起，声息都难出。",
    foeMute: 3,
    school: "any",
  },
  lateLeech: {
    id: "lateLeech",
    name: "抽龙",
    cost: 3,
    type: "skill",
    text: "敌扣劲 2 息。你立刻回 3 劲。",
    flavor: "龙气也能抽。",
    foeQiBurn: 2,
    energyNext: 3,
    school: "any",
  },
  lateHand: {
    id: "lateHand",
    name: "削册",
    cost: 2,
    type: "skill",
    text: "敌手牌上限 -2，持续 2 息。",
    flavor: "册页少了，招也少了。",
    foeHandTax: 2,
    school: "any",
  },
  latePouch: {
    id: "latePouch",
    name: "封库",
    cost: 2,
    type: "skill",
    text: "敌禁药 3 息。你禁药 1 息。",
    flavor: "库门一封，两边都摸不着。",
    foeNoBag: 3,
    noBag: 1,
    school: "any",
  },
  jinwuToken: {
    id: "jinwuToken",
    name: "金吾卫令",
    cost: 1,
    type: "skill",
    text: "获得 5 点格挡。获得 2 层铁布。",
    flavor: "铜令一亮，巡卒收刀半寸。",
    block: 5,
    thorns: 2,
    school: "any",
  },
  peonyBrew: {
    id: "peonyBrew",
    name: "牡丹酿",
    cost: 0,
    type: "skill",
    text: "回复 2 点生命。下回合 +1 劲力；获得 1 层滞手。",
    flavor: "花香入喉。气足，皮薄。",
    heal: 2,
    energyNext: 1,
    frail: 1,
    school: "any",
  },
  drunkFist: {
    id: "drunkFist",
    name: "醉拳",
    cost: 2,
    type: "attack",
    text: "造成 10 点伤害。贴身再 +3。",
    flavor: "醉了打人。醒了挨打。",
    damage: 10,
    nearBonus: 3,
    school: "palm",
  },

  ultQiBurst: {
    id: "ultQiBurst",
    name: "势爆绝",
    cost: 2,
    type: "attack",
    text: "绝招：势≥3。造成 14 点伤害。",
    flavor: "势足则绝。",
    damage: 14,
    ultimate: { qiMin: 3 },
    school: "any",
  },
  ultIronWall: {
    id: "ultIronWall",
    name: "铁壁",
    cost: 2,
    type: "skill",
    text: "绝招：格挡≥5。格挡 +10（满足前置时翻倍）。",
    flavor: "盾在人在。",
    block: 10,
    ultimate: { blockMin: 5, doubleBlock: true },
    school: "any",
  },

  // §31.11 六系绝招：各系一张，前置各异，扣住系别特色
  ultSaber: {
    id: "ultSaber",
    name: "回马刀",
    cost: 3,
    type: "attack",
    text: "绝招：上回合挨过敌招。伤 18，击退 1。",
    flavor: "刀埋在鞘里，等的就是他先出手。",
    damage: 18,
    knock: 1,
    ultimate: { foeHitLastTurn: true },
    school: "saber",
  },
  ultSword: {
    id: "ultSword",
    name: "剑走龙蛇",
    cost: 3,
    type: "attack",
    text: "绝招：敌裂创 ≥4。伤 10，裂创 +2。",
    flavor: "伤口多了，剑自己找路。",
    damage: 10,
    bleed: 2,
    ultimate: { bleedMin: 4 },
    school: "sword",
  },
  ultSpear: {
    id: "ultSpear",
    name: "枪挑一线",
    cost: 3,
    type: "attack",
    text: "绝招：距离 ≥3。伤 20。",
    flavor: "枪尖到的地方，就是一线天。",
    damage: 20,
    ultimate: { distMin: 3 },
    school: "spear",
  },
  ultStaff: {
    id: "ultStaff",
    name: "罗汉伏魔",
    cost: 3,
    type: "attack",
    text: "绝招：本回合已出 2 张攻击。伤 12，敌眩晕 1 段。",
    flavor: "棍到第三下，才见罗汉。",
    damage: 12,
    foeStun: 1,
    ultimate: { attacksMin: 2 },
    school: "staff",
  },
  ultHook: {
    id: "ultHook",
    name: "摘星手",
    cost: 2,
    type: "attack",
    text: "绝招：敌缴械中。伤 12，拉近 1，续缴械 1 息。",
    flavor: "他手里没了东西，天上的星也摘得。",
    damage: 12,
    pullEnemy: 1,
    foeDisarm: 1,
    ultimate: { foeDisarmed: true },
    school: "hook",
  },
  ultPalm: {
    id: "ultPalm",
    name: "开碑",
    cost: 3,
    type: "attack",
    text: "绝招：敌贴墙。伤 22。",
    flavor: "掌到墙上，碑和人一起裂。",
    damage: 22,
    ultimate: { foeAtWall: true },
    school: "palm",
  },
  varBackwater: {
    id: "varBackwater",
    name: "背水一战",
    cost: 2,
    type: "attack",
    text: "变式：HP≤20% 耗劲 0；否则造成 8 点伤害。",
    flavor: "绝境反扑。",
    damage: 8,
    variant: {
      kind: "lowHp",
      threshold: 0.2,
      labelA: "常势",
      labelB: "背水",
      costZeroOnB: true,
    },
    school: "any",
  },
  varOverhand: {
    id: "varOverhand",
    name: "全力一击",
    cost: 2,
    type: "attack",
    text: "变式：HP≥80% 伤害 +50%；否则造成 8 点伤害。",
    flavor: "满血出全力。",
    damage: 8,
    variant: {
      kind: "highHp",
      threshold: 0.8,
      labelA: "全力",
      labelB: "常势",
      damageMulA: 1.5,
    },
    school: "any",
  },
  comboPalm: {
    id: "comboPalm",
    name: "双掌合击",
    cost: 2,
    type: "attack",
    text: "组合：后场该系同行。伤 14，推 1 格。",
    flavor: "同门合击。",
    damage: 14,
    knock: 1,
    tags: ["组合"],
    requiresAssist: true,
    school: "palm",
  },
  comboSaber: {
    id: "comboSaber",
    name: "双刀交剪",
    cost: 2,
    type: "attack",
    text: "组合：后场该系同行。伤 16；贴身再 +6。",
    flavor: "同门合击。",
    damage: 16,
    tags: ["组合"],
    requiresAssist: true,
    school: "saber",
  },
  comboSpear: {
    id: "comboSpear",
    name: "枪棍齐戳",
    cost: 2,
    type: "attack",
    text: "组合：需后场有该系同行（异系伙伴=组合技）。伤 11，破绽 +2。",
    flavor: "同门合击。",
    damage: 11,
    tags: ["组合"],
    requiresAssist: true,
    school: "spear",
  },
  comboSword: {
    id: "comboSword",
    name: "双剑映月",
    cost: 2,
    type: "attack",
    text: "组合：需后场有该系同行（异系伙伴=组合技）。伤 9，封脉滞步。",
    flavor: "同门合击。",
    damage: 9,
    tags: ["组合"],
    requiresAssist: true,
    school: "sword",
  },
  comboStaff: {
    id: "comboStaff",
    name: "桩棍齐扫",
    cost: 2,
    type: "attack",
    text: "组合：需后场有该系同行（异系伙伴=组合技）。伤 8，格挡 +6。",
    flavor: "同门合击。",
    damage: 8,
    block: 6,
    tags: ["组合"],
    requiresAssist: true,
    school: "staff",
  },
  comboHook: {
    id: "comboHook",
    name: "钩索齐发",
    cost: 2,
    type: "attack",
    text: "组合：需后场有该系同行（异系伙伴=组合技）。拉近 1，伤 8。",
    flavor: "同门合击。",
    damage: 8,
    pullEnemy: 1,
    tags: ["组合"],
    requiresAssist: true,
    school: "hook",
  },
  ...ROGUE_CARD_DEFS,
};

export const UPGRADES: Partial<Record<CardId, CardId>> = {
  strike: "strike2",
  defend: "defend2",
  push: "push2",
  charge: "charge2",
  advance: "advance2",
  mend: "mend2",
  haste: "haste2",
  follow: "follow2",
  chain: "chain2",
  gather: "gather2",
  finisher: "finisher2",
};

export const BASICS: CardId[] = [
  "strike",
  "defend",
  "push",
  "charge",
  "advance",
  "mend",
  "brace",
  "combo",
  "setup",
  "gather",
];
export const VERBS: CardId[] = [
  "drawcut",
  "backpalm",
  "split",
  "close",
  "elbow",
  "sweep",
  "cut",
  "thrust",
  "pierce",
  "plant",
  "hookpull",
  "bleedcut",
  "expose",
  "thorns",
  "inbreath",
  "combo",
  "haste",
  "follow",
  "twinpalm",
  "brace",
  "chain",
  "gather",
  "setup",
  "finisher",
  "weave",
  "echo",
  "ironform",
  "marking",
  "rift",
  "mirror",
  "layer",
  "tide",
  "burySlash",
  "buryBleed",
  "buryKnock",
  "buryWard",
  "salve",
  "unbind",
  "sidestep",
  "suture",
  "cauterize",
  "bindwound",
  "qiPulse",
  "palmSeal",
  "saberBleed",
  "spearLock",
  "swordMute",
  "staffBind",
  "hookDisarm",
  "skillLock",
  "pouchSeal",
  "handCut",
  "qiLeech",
  "comboPay",
  "midStrike",
  "midGuard",
  "lateAnvil",
  "lateChain",
  "lateMute",
];

export const STARTER_DECK: CardId[] = [
  "strike",
  "strike",
  "strike",
  "defend",
  "push",
  "charge",
  "advance",
  "advance",
  "mend",
  "defend",
  "setup",
  "gather",
  "combo",
  "finisher",
  "follow",
  "weave",
  "burySlash",
  "salve",
  "sidestep",
];

export const STARTER = {
  playerHp: BASE_HP,
  enemyHp: 56,
  enemyDamage: 18,
  playerPos: 0,
  enemyPos: 5,
  /** 劲力上限（蓝条） */
  energy: 10,
  /** 开局当前劲力 */
  energyStart: 8,
  /** 每回基础回劲 */
  energyRegen: 4,
  gold: 49,
  floor: 1,
};

export const HEROES: HeroDef[] = [
  {
    id: "rail",
    name: "轨刃",
    title: "破门刀",
    sect: "推宫一门",
    verb: "推、撞、占步",
    hp: "28",
    crime: "比武已经判了推开，你还是拔了真刀。",
    pitch: "码头上替人踹过不少门。港律要找你算这一笔。",
    locked: false,
  },
  {
    id: "seer",
    name: "镜亭",
    title: "观气客",
    sect: "镜廷残谱",
    verb: "观气、破绽、连手",
    hp: "24",
    crime: "改过对方已经亮出的招。",
    pitch: "镜廷的人，观气不观这一掌。税卡缺的那一笔，要从案上找回来。",
    locked: false,
  },
  {
    id: "sapper",
    name: "沈夯",
    title: "桩师",
    sect: "垂街机关",
    verb: "落桩、占格、反震",
    hp: "32",
    crime: "不该下桩的地方，你落了一根。",
    pitch: "缆厂出身。桩还认你，官道还不认。",
    locked: false,
  },
];

export const TECHNIQUES: Record<TechniqueId, TechniqueDef> = {
  longPush: {
    id: "longPush",
    name: "开山劲",
    text: "击退再多 1 格。",
    flavor: "门比人先开。",
    chapter: "dock",
  },
  backstep: {
    id: "backstep",
    name: "回身",
    text: "进步无路则后退。",
    flavor: "前脚不行，后脚还在。",
    chapter: "dock",
  },
  keepGuard: {
    id: "keepGuard",
    name: "残劲",
    text: "收势时留下 4 点格挡。",
    flavor: "力卸完，腕还硬。",
    chapter: "dock",
  },
  hardWall: {
    id: "hardWall",
    name: "震壁",
    text: "撞壁伤害至少 12 点。",
    flavor: "壁比门硬，人也比门硬。",
    chapter: "dock",
  },
  brightBlade: {
    id: "brightBlade",
    name: "亮刀残谱",
    text: "相邻时攻击伤害 +3。",
    flavor: "刀已经亮了，掌就不必藏。",
    chapter: "dock",
    school: "saber",
  },
  bodyCheck: {
    id: "bodyCheck",
    name: "对撞",
    text: "进步若撞上人，造成 6 点伤害。",
    flavor: "让开的那一步，改成撞。",
    chapter: "dock",
  },
  heelStake: {
    id: "heelStake",
    name: "后桩",
    text: "开场在第 2 步落一根桩。",
    flavor: "先把退的那一步钉上。",
    chapter: "dock",
    school: "staff",
  },
  shortCharge: {
    id: "shortCharge",
    name: "绊步",
    text: "对方冲锋少走 1 步。",
    flavor: "巷里迈不开第三步。",
    chapter: "alley",
  },
  ghostStep: {
    id: "ghostStep",
    name: "镜步",
    text: "进步可穿过桩。",
    flavor: "桩认人，不认影。",
    chapter: "alley",
  },
  trapWard: {
    id: "trapWard",
    name: "识机",
    text: "你不受机关格伤害。",
    flavor: "机簧响的时候，脚已经不在那儿。",
    chapter: "alley",
  },
  tether: {
    id: "tether",
    name: "纤力",
    text: "收势时若相隔超过 2 格，把对方拉近 1 格。",
    flavor: "缆还在手上。",
    chapter: "alley",
    school: "hook",
  },
  closeCut: {
    id: "closeCut",
    name: "巷刃",
    text: "抽刀始终按相邻结算。",
    flavor: "巷窄，刀不必出鞘。",
    chapter: "alley",
    school: "saber",
  },
  delayGuard: {
    id: "delayGuard",
    name: "等手",
    text: "对方蓄势时，你获得 3 点格挡。",
    flavor: "他要过一拍。你就卸这一拍。",
    chapter: "court",
  },
  throne: {
    id: "throne",
    name: "门墙",
    text: "你在第 1 步时，卸力类格挡 +4。",
    flavor: "背贴着门，力有地方去。",
    chapter: "court",
  },
  nightStep: {
    id: "nightStep",
    name: "夜步残谱",
    text: "开战先有 1 点格挡。",
    flavor: "井底下的人，先把气沉住。",
    chapter: "dock",
  },
  leftover: {
    id: "leftover",
    name: "余劲",
    text: "收势时留下 1 点劲力到下回合。",
    flavor: "这一拍没打完，下一拍还热。",    chapter: "dock",
  },
  rebound: {
    id: "rebound",
    name: "回桩",
    text: "你挨打时回敬 3 点。",
    flavor: "力打在桩上，桩还人。",
    chapter: "dock",
    school: "staff",
  },
  stackHand: {
    id: "stackHand",
    name: "多手",
    text: "手里多留一张。",
    flavor: "谱多一页，步就多一拍。",
    chapter: "dock",
  },
  // §31.19 分系外功：各武器分化出各自的外功，奖励池只出「本系 + 通用」。
  ironPalm: {
    id: "ironPalm",
    name: "铁掌印",
    text: "撞壁伤害 +6。",
    flavor: "印在墙上，也印在骨上。",
    chapter: "dock",
    school: "palm",
  },
  softPalm: {
    id: "softPalm",
    name: "绵里针",
    text: "你的格挡牌额外 +2。",
    flavor: "棉花里藏着针，架住才知道。",
    chapter: "dock",
    school: "palm",
  },
  piercingPalm: {
    id: "piercingPalm",
    name: "透骨劲",
    text: "击退再远 1 格。",
    flavor: "掌力穿过皮肉，落到桩子上。",
    chapter: "dock",
    school: "palm",
  },
  saberGrudge: {
    id: "saberGrudge",
    name: "衔恨刀",
    text: "上回合挨过打，本回合攻击再 +2（与埋招叠加）。",
    flavor: "刀记着疼，比人记得牢。",
    chapter: "alley",
    school: "saber",
  },
  spearWind: {
    id: "spearWind",
    name: "枪风",
    text: "相隔 3 格以上时，攻击 +3。",
    flavor: "枪头未到，风先到了。",
    chapter: "alley",
    school: "spear",
  },
  longMarch: {
    id: "longMarch",
    name: "长驱",
    text: "进步多走 1 步。",
    flavor: "枪出如龙，步不停。",
    chapter: "alley",
    school: "spear",
  },
  pikeBrace: {
    id: "pikeBrace",
    name: "拒马",
    text: "对方蓄势时，你获得 2 点格挡。",
    flavor: "枪尖朝外，就是半堵墙。",
    chapter: "court",
    school: "spear",
  },
  swordRain: {
    id: "swordRain",
    name: "剑雨",
    text: "目标裂创 ≥3 层时，你的攻击 +3。",
    flavor: "伤口越多，剑越密。",
    chapter: "alley",
    school: "sword",
  },
  swordScreen: {
    id: "swordScreen",
    name: "剑幕",
    text: "不贴身时，你的格挡牌 +3。",
    flavor: "剑光铺开，就是帘子。",
    chapter: "court",
    school: "sword",
  },
  flowSword: {
    id: "flowSword",
    name: "流水剑",
    text: "收势时再多留 1 点劲力到下回合。",
    flavor: "剑势不断，劲力不散。",
    chapter: "court",
    school: "sword",
  },
  stakeArmor: {
    id: "stakeArmor",
    name: "桩甲",
    text: "场上有桩时，每回合开局格挡 +2。",
    flavor: "桩立住了，人就硬了。",
    chapter: "dock",
    school: "staff",
  },
  heavyStaff: {
    id: "heavyStaff",
    name: "沉棍",
    text: "击退再远 1 格。",
    flavor: "棍重三分，人退三步。",
    chapter: "dock",
    school: "staff",
  },
  barbedHook: {
    id: "barbedHook",
    name: "倒刺钩",
    text: "每次把对方拉近时，附 3 点伤。",
    flavor: "钩上有倒刺，进来就得留东西。",
    chapter: "alley",
    school: "hook",
  },
  hookVeil: {
    id: "hookVeil",
    name: "钩帘",
    text: "对方被缴械时，你的格挡牌 +3。",
    flavor: "他没了家伙，你的钩子就是门帘。",
    chapter: "court",
    school: "hook",
  },
};

export const HEARTS: Record<HeartId, HeartDef> = {
  iron: {
    id: "iron",
    name: "劲力",
    text: "偏攻。开战先机略高，出招更沉半成。",
    flavor: "先抢半步，刀才认人。",
  },
  breath: {
    id: "breath",
    name: "命数",
    text: "偏防。命数上限 4（默认 3）。",
    flavor: "多留一口气在体外。",
  },
  empty: {
    id: "empty",
    name: "资装",
    text: "开局多银与凡药、赤铜，方便早做买卖。",
    flavor: "路上要银，也要药。",
  },
};

export const ENEMIES: Record<EnemyId, EnemyDef> = {
  catcher: {
    id: "catcher",
    name: "赵捕",
    title: "码头官差",
    hp: 56,
    pos: 5,
    skill: "亮刀",
    pitch: "「刀在这儿。名册上没有你。」",
    remnant: "brightBlade",
    pattern: [{ kind: "strike", damage: 18 }, { kind: "guard", block: 8 }, { kind: "breathe", amount: 3 }],
  },
  escort: {
    id: "escort",
    name: "沈镖",
    title: "走水护镖",
    hp: 72,
    pos: 3,
    skill: "冲锋",
    pitch: "「让开。这箱不是给你看的。」",
    remnant: "bodyCheck",
    pattern: [{ kind: "charge", damage: 18, steps: 3 }, { kind: "guard", block: 8 }, { kind: "strike", damage: 14 }],
  },
  piler: {
    id: "piler",
    name: "桩阿大",
    title: "垂街残徒",
    hp: 74,
    pos: 4,
    skill: "落桩",
    pitch: "「先下桩。船今晚不接除名。」",
    remnant: "heelStake",
    pattern: [{ kind: "stake" }, { kind: "guard", block: 8 }, { kind: "strike", damage: 19 }],
  },
  hauler: {
    id: "hauler",
    name: "纤佬",
    title: "岸缆",
    hp: 72,
    pos: 4,
    skill: "拉",
    pitch: "「缆在我手里。巷里的人叫我拦住往北的。」",
    remnant: "tether",
    pattern: [{ kind: "pull", steps: 2 }, { kind: "guard", block: 6 }, { kind: "strike", damage: 18 }],
  },
  alley: {
    id: "alley",
    name: "巷刃",
    title: "垂街夜行",
    hp: 70,
    pos: 3,
    skill: "抢步",
    pitch: "「问半页纸的人，巷里只有一步。」",
    remnant: "closeCut",
    pattern: [{ kind: "lunge", damage: 18 }, { kind: "guard", block: 6 }, { kind: "breathe", amount: 3 }],
  },
  trapper: {
    id: "trapper",
    name: "簧二",
    title: "簧片",
    hp: 70,
    pos: 4,
    skill: "下机",
    pitch: "「北栅是镜廷的。脚底下。」",
    remnant: "trapWard",
    pattern: [{ kind: "trap" }, { kind: "guard", block: 6 }, { kind: "strike", damage: 18 }],
  },
  delay: {
    id: "delay",
    name: "迟手裴",
    title: "镜廷过客",
    hp: 78,
    pos: 4,
    skill: "蓄势",
    pitch: "「这一拍让给你。名册要写得干净。」",
    remnant: "delayGuard",
    pattern: [{ kind: "windup" }, { kind: "strike", damage: 26 }, { kind: "guard", block: 10 }],
  },
  twin: {
    id: "twin",
    name: "影步",
    title: "镜中人",
    hp: 72,
    pos: 3,
    skill: "换位",
    pitch: "「你站的是我的位置。名册盖住你的时候，留下了我。」",
    remnant: "ghostStep",
    pattern: [{ kind: "swap" }, { kind: "guard", block: 6 }, { kind: "strike", damage: 19 }],
  },
  lord: {
    id: "lord",
    name: "门墙顾",
    title: "门墙",
    hp: 88,
    pos: 4,
    skill: "冲、桩、劈",
    pitch: "「名册在门里。墨还没干。」",
    remnant: "throne",
    pattern: [{ kind: "charge", damage: 16, steps: 2 }, { kind: "guard", block: 10 }, { kind: "stake" }, { kind: "strike", damage: 20 }],
    patternSets: [
      [{ kind: "barrage", damage: 8, hits: 2 }, { kind: "windup" }, { kind: "strike", damage: 22 }, { kind: "shatter", amount: 10 }],
    ],
  },
  usurper: {
    id: "usurper",
    name: "夺玺者",
    title: "谋逆主脑",
    hp: 120,
    pos: 4,
    skill: "冲、连打、架",
    pitch: "「印玺该换手了。你们三个，来得正好。」",
    remnant: "throne",
    // §31.10 馆主长兵：隔一格也能打到（踢馆线极难的空间压迫）。
    reach: 2,
    pattern: [
      { kind: "guard", block: 12 },
      { kind: "charge", damage: 18, steps: 2 },
      { kind: "counter", form: "slash" },
      { kind: "barrage", damage: 12, hits: 3 },
      { kind: "strike", damage: 24 },
    ],
  },
  bandit: {
    id: "bandit",
    name: "岗花子",
    title: "院外蹲手",
    hp: 110,
    pos: 4,
    skill: "恶手",
    pitch: "「过帖的人身上有油水。岗上不讲让。」",
    remnant: "hardWall",
    pattern: [{ kind: "shatter", amount: 8 }, { kind: "guard", block: 8 }, { kind: "bleedcut", damage: 10, bleed: 3 }, { kind: "charge", damage: 14, steps: 2 }, { kind: "barrage", damage: 6, hits: 2 }],
  },
  thief: {
    id: "thief",
    name: "剪绺",
    title: "驿路窃贼",
    hp: 58,
    pos: 3,
    skill: "摸袋",
    pitch: "「你看别处。我看你腰。」",
    remnant: "ghostStep",
    pattern: [{ kind: "lunge", damage: 14 }, { kind: "guard", block: 5 }, { kind: "strike", damage: 12 }],
  },
  hillBandit: {
    id: "hillBandit",
    name: "岗匪",
    title: "山路拦客",
    hp: 88,
    pos: 4,
    skill: "拦路",
    pitch: "「过山要钱。过刀也行。」",
    remnant: "bodyCheck",
    pattern: [{ kind: "shatter", amount: 8 }, { kind: "guard", block: 6 }, { kind: "charge", damage: 16, steps: 2 }, { kind: "strike", damage: 19 }],
  },
  riverThug: {
    id: "riverThug",
    name: "水匪",
    title: "渡口闲刀",
    hp: 72,
    pos: 4,
    skill: "扳船",
    pitch: "「岸上的货，水里也认价。」",
    remnant: "longPush",
    pattern: [{ kind: "pull", steps: 2 }, { kind: "guard", block: 6 }, { kind: "strike", damage: 17 }, { kind: "shatter", amount: 6 }],
  },
  raider: {
    id: "raider",
    name: "潮口",
    title: "潮口",
    hp: 76,
    pos: 4,
    skill: "拉缆",
    pitch: "「岸上的货，潮里也认。」",
    remnant: "longPush",
    pattern: [{ kind: "shatter", amount: 8 }, { kind: "pull", steps: 2 }, { kind: "breathe", amount: 3 }, { kind: "strike", damage: 19 }],
  },
  robber: {
    id: "robber",
    name: "缆刀",
    title: "缆厂夜手",
    hp: 68,
    pos: 3,
    skill: "抢步",
    pitch: "「契不在身上，刀也认。」",
    remnant: "shortCharge",
    pattern: [{ kind: "lunge", damage: 18 }, { kind: "breathe", amount: 3 }, { kind: "guard", block: 6 }],
  },
  smuggler: {
    id: "smuggler",
    name: "换口盐",
    title: "换口的人",
    hp: 72,
    pos: 4,
    skill: "卸力",
    pitch: "「官盐朝西。我朝东。」",
    remnant: "keepGuard",
    pattern: [{ kind: "guard", block: 12 }, { kind: "windup" }, { kind: "strike", damage: 20 }],
  },
  thug: {
    id: "thug",
    name: "巷霸",
    title: "巷口",
    hp: 68,
    pos: 3,
    skill: "回身",
    pitch: "「往北的人，把口袋留下。」",
    remnant: "backstep",
    pattern: [{ kind: "shatter", amount: 8 }, { kind: "guard", block: 7 }, { kind: "strike", damage: 17 }, { kind: "charge", damage: 16, steps: 2 }],
  },
  intruder: {
    id: "intruder",
    name: "夜客",
    title: "破门的人",
    hp: 42,
    pos: 4,
    skill: "劈",
    pitch: "「屋里那人，帖还没递。」",
    remnant: "backstep",
    pattern: [{ kind: "strike", damage: 13 }, { kind: "guard", block: 6 }, { kind: "breathe", amount: 3 }, { kind: "lunge", damage: 12 }],
  },
  brute: {
    id: "brute",
    name: "坡蹲",
    title: "坡上蹲手",
    hp: 76,
    pos: 4,
    skill: "撞岗",
    pitch: "「岗是我的。人留下。」",
    remnant: "bodyCheck",
    pattern: [{ kind: "charge", damage: 17, steps: 2 }, { kind: "guard", block: 8 }, { kind: "strike", damage: 19 }],
  },
  cavehand: {
    id: "cavehand",
    name: "缝手",
    title: "潮缝",
    hp: 74,
    pos: 3,
    skill: "拖",
    pitch: "「缝里的人，不认名册。」",
    remnant: "tether",
    pattern: [{ kind: "pull", steps: 2 }, { kind: "breathe", amount: 3 }, { kind: "lunge", damage: 18 }],
  },
  warden: {
    id: "warden",
    name: "岗老",
    title: "岗门",
    hp: 80,
    pos: 4,
    skill: "蓄势",
    pitch: "「过岗要留下一刀。」",
    remnant: "delayGuard",
    pattern: [{ kind: "windup" }, { kind: "strike", damage: 26 }, { kind: "guard", block: 10 }],
  },
  inkhand: {
    id: "inkhand",
    name: "墨手",
    title: "税卡夜笔",
    hp: 44,
    pos: 4,
    skill: "点墨",
    pitch: "「案下那一笔，还没干。」",
    remnant: "leftover",
    pattern: [{ kind: "strike", damage: 13 }, { kind: "breathe", amount: 4 }, { kind: "guard", block: 7 }],
  },
  bookcut: {
    id: "bookcut",
    name: "裁页",
    title: "潮祠刀笔",
    hp: 72,
    pos: 4,
    skill: "抽刀",
    pitch: "「页裁过。名就短一截。」",
    remnant: "stackHand",
    pattern: [{ kind: "lunge", damage: 17 }, { kind: "guard", block: 6 }, { kind: "strike", damage: 16 }],
  },
  nametaker: {
    id: "nametaker",
    name: "夺名吏",
    title: "岗上收名",
    hp: 82,
    pos: 4,
    skill: "蓄势",
    pitch: "「名留下。人可以走。」",
    remnant: "leftover",
    pattern: [{ kind: "windup" }, { kind: "strike", damage: 26 }, { kind: "breathe", amount: 3 }],
  },
  glasspin: {
    id: "glasspin",
    name: "镜钉",
    title: "潮口抽钉",
    hp: 74,
    pos: 4,
    skill: "拉",
    pitch: "「镜子里的钉子，要拔出来。」",
    remnant: "rebound",
    pattern: [{ kind: "pull", steps: 2 }, { kind: "guard", block: 6 }, { kind: "strike", damage: 18 }],
  },
  knotboss: {
    id: "knotboss",
    name: "死结手",
    title: "坞里那结",
    hp: 76,
    pos: 4,
    skill: "拉缆",
    pitch: "「结是死的。人不是。」",
    remnant: "leftover",
    pattern: [{ kind: "pull", steps: 2 }, { kind: "guard", block: 8 }, { kind: "lunge", damage: 17 }],
  },
  stakeboss: {
    id: "stakeboss",
    name: "钉桩的",
    title: "缆厂桩师",
    hp: 48,
    pos: 4,
    skill: "落桩",
    pitch: "「这根桩是我钉的。你把它拔了。」",
    remnant: "rebound",
    pattern: [{ kind: "stake" }, { kind: "guard", block: 8 }, { kind: "strike", damage: 14 }],
  },
  tutorPace: {
    id: "tutorPace",
    name: "步阿宽",
    title: "岗棚教习",
    hp: 30,
    pos: 4,
    skill: "让步",
    pitch: "“步是让出来的。你站在我要踩的地方，就是自己找撞。”",
    remnant: "leftover",
    pattern: [{ kind: "charge", damage: 10, steps: 2 }],
  },
  tutorWard: {
    id: "tutorWard",
    name: "掌阿稳",
    title: "岸上教习",
    hp: 32,
    pos: 4,
    skill: "卸力",
    pitch: "“掌打在卸上，力才回去。硬接会倒。”",
    remnant: "leftover",
    pattern: [{ kind: "strike", damage: 11 }],
  },
  tutorEdge: {
    id: "tutorEdge",
    name: "谱阿正",
    title: "巷口教习",
    hp: 30,
    pos: 4,
    skill: "分谱",
    pitch: "“拳谱是拳谱。刀谱是刀谱。别混着使。”",
    remnant: "leftover",
    pattern: [{ kind: "strike", damage: 10 }],
  },
  jinwu: {
    id: "jinwu",
    name: "金吾卒",
    title: "天津桥巡",
    hp: 68,
    pos: 4,
    skill: "拦路",
    pitch: "「桥上夜巡。无帖者，留下。」",
    remnant: "keepGuard",
    pattern: [{ kind: "guard", block: 10 }, { kind: "strike", damage: 16 }, { kind: "breathe", amount: 2 }],
  },
  canalThug: {
    id: "canalThug",
    name: "漕帮打手",
    title: "洛水私口",
    hp: 72,
    pos: 3,
    skill: "扑岸",
    pitch: "「漕口的账，不认官印。」",
    remnant: "bodyCheck",
    pattern: [{ kind: "charge", damage: 16, steps: 2 }, { kind: "strike", damage: 15 }, { kind: "guard", block: 6 }],
  },
  brothelGuard: {
    id: "brothelGuard",
    name: "平康护院",
    title: "坊门刀",
    hp: 64,
    pos: 4,
    skill: "拦门",
    pitch: "「姑娘的局，外人别闯。」",
    remnant: "closeCut",
    pattern: [{ kind: "lunge", damage: 15 }, { kind: "guard", block: 8 }, { kind: "strike", damage: 14 }],
  },
  jailer: {
    id: "jailer",
    name: "狱卒",
    title: "府衙侧牢",
    hp: 70,
    pos: 4,
    skill: "锁步",
    pitch: "「枷还热。你要试，就进来。」",
    remnant: "hardWall",
    pattern: [{ kind: "stake" }, { kind: "strike", damage: 17 }, { kind: "guard", block: 9 }],
  },
};

Object.assign(ENEMIES, GENERATED_ENEMIES);

export const SPAR_ENEMIES: EnemyId[] = ["tutorPace", "tutorWard", "tutorEdge"];

export function isSparEnemy(id: EnemyId): boolean {
  return SPAR_ENEMIES.includes(id);
}

export const ENEMY_WEAPON: Record<EnemyId, WeaponId> = {
  catcher: "saber",
  escort: "saber",
  piler: "staff",
  hauler: "hook",
  alley: "saber",
  trapper: "staff",
  delay: "sword",
  twin: "sword",
  lord: "palm",
  usurper: "saber",
  bandit: "saber",
  raider: "hook",
  robber: "saber",
  smuggler: "sword",
  thug: "palm",
  thief: "palm",
  hillBandit: "saber",
  riverThug: "hook",
  intruder: "palm",
  brute: "palm",
  cavehand: "hook",
  warden: "staff",
  inkhand: "sword",
  bookcut: "saber",
  nametaker: "sword",
  glasspin: "hook",
  knotboss: "hook",
  stakeboss: "staff",
  tutorPace: "palm",
  tutorWard: "palm",
  tutorEdge: "saber",
  jinwu: "saber",
  canalThug: "palm",
  brothelGuard: "saber",
  jailer: "staff",
};

Object.assign(ENEMY_WEAPON, GENERATED_ENEMY_WEAPON);

export const ENEMY_PACE: Partial<Record<EnemyId, number>> = {
  catcher: 4,
  escort: 5,
  piler: 3,
  delay: 2,
  trapper: 9,
  alley: 6,
  twin: 8,
  glasspin: 8,
  robber: 6,
  thug: 6,
  stakeboss: 4,
  hauler: 5,
  bandit: 8,
  thief: 7,
  hillBandit: 6,
  riverThug: 5,
  raider: 5,
  brute: 5,
  cavehand: 6,
  bookcut: 6,
  knotboss: 5,
  lord: 4,
  usurper: 6,
  smuggler: 4,
  warden: 3,
  nametaker: 3,
  inkhand: 5,
  intruder: 5,
};

export function enemyPace(id: EnemyId): number {
  return ENEMY_PACE[id] ?? 5;
}

/** Foe energy budget per round — weak hands 1, elites 3–4. */
export const ENEMY_ENERGY: Partial<Record<EnemyId, number>> = {
  catcher: 1,
  escort: 2,
  hauler: 2,
  alley: 2,
  trapper: 2,
  cavehand: 2,
  bookcut: 2,
  glasspin: 2,
  raider: 2,
  robber: 2,
  thug: 2,
  smuggler: 2,
  inkhand: 1,
  intruder: 1,
  stakeboss: 1,
  tutorPace: 1,
  tutorWard: 1,
  tutorEdge: 1,
  jinwu: 2,
  canalThug: 2,
  brothelGuard: 2,
  jailer: 2,
  bandit: 4,
  thief: 2,
  hillBandit: 2,
  riverThug: 2,
  brute: 4,
  piler: 2,
  delay: 1,
  twin: 4,
  warden: 4,
  knotboss: 4,
  nametaker: 5,
  lord: 6,
  usurper: 7,
};

Object.assign(ENEMY_ENERGY, GENERATED_ELITE_ENERGY);

export function enemyEnergyMax(id: EnemyId): number {
  const base = ENEMY_ENERGY[id] ?? 2;
  // 劲力蓝条化后敌上限抬到约 6–10
  return Math.min(10, 4 + base * 2);
}

export const CHAPTER_TECH: Record<ChapterId, TechniqueId[]> = {
  dock: ["longPush", "backstep", "keepGuard", "hardWall", "leftover", "rebound", "stackHand"],
  alley: ["shortCharge", "ghostStep", "trapWard"],
  court: ["delayGuard", "throne"],
  isle: ["brightBlade", "bodyCheck"],
};

export const CHALLENGE: EnemyId[] = [
  "bandit",
  "raider",
  "robber",
  "smuggler",
  "thug",
  "thief",
  "hillBandit",
  "riverThug",
  "brute",
  "cavehand",
  "warden",
];

export const CHAPTERS: Record<
  ChapterId,
  { name: string; kicker: string; next: ChapterId | null; index: number }
> = {
  dock: { name: "港律", kicker: "码头", next: "alley", index: 1 },
  alley: { name: "巷律", kicker: "垂街", next: "court", index: 2 },
  court: { name: "门律", kicker: "宫阙", next: "isle", index: 3 },
  isle: { name: "潮屿", kicker: "潮门", next: null, index: 4 },
};

export function intentLabel(intent: Intent): string {
  if (intent.kind === "strike") return `打击 ${intent.damage}`;
  if (intent.kind === "charge") return `冲锋 ${intent.steps} · ${intent.damage}`;
  if (intent.kind === "stake") return "落桩";
  if (intent.kind === "pull") return `拉 ${intent.steps}`;
  if (intent.kind === "trap") return "下机";
  if (intent.kind === "windup") return "蓄势";
  if (intent.kind === "lunge") return `抢步 ${intent.damage}`;
  if (intent.kind === "swap") return "换位";
  if (intent.kind === "barrage") return `连打 ${intent.hits} · ${intent.damage}`;
  if (intent.kind === "guard") return `卸力 ${intent.block}`;
  if (intent.kind === "bleedcut") return `刀创 ${intent.damage}`;
  if (intent.kind === "counter") return "埋招";
  if (intent.kind === "mend") return `金创 ${intent.heal}`;
  if (intent.kind === "seal") return "封脉";
  if (intent.kind === "shatter") return `裂盾 ${intent.amount}`;
  if (intent.kind === "breathe") return `吐纳 +${intent.amount}`;
  if (intent.kind === "retreat") return `撤 ${intent.steps}`;
  if (intent.kind === "pestle") return `韦陀杵 ${intent.damage}`;
  if (intent.kind === "dust") return "迷眼";
  if (intent.kind === "shackle") return "锁链";
  if (intent.kind === "dodge") return "闪避";
  if (intent.kind === "endure") return "霸体";
  if (intent.kind === "sig") return SIGNATURE_BREAK[intent.id as keyof typeof SIGNATURE_BREAK]?.label ?? "绝招";
  return "换位";
}

/** 意图条标题：不含数字（数字只出现在右侧一处）。 */
export function intentShortName(intent: Intent): string {
  if (intent.kind === "strike") return "打击";
  if (intent.kind === "charge") return "冲锋";
  if (intent.kind === "stake") return "落桩";
  if (intent.kind === "pull") return "拉近";
  if (intent.kind === "trap") return "下机";
  if (intent.kind === "windup") return "蓄势";
  if (intent.kind === "lunge") return "抢步";
  if (intent.kind === "swap") return "换位";
  if (intent.kind === "barrage") return "连打";
  if (intent.kind === "guard") return "卸力";
  if (intent.kind === "bleedcut") return "刀创";
  if (intent.kind === "counter") return "埋招";
  if (intent.kind === "mend") return "金创";
  if (intent.kind === "seal") return "封脉";
  if (intent.kind === "shatter") return "裂盾";
  if (intent.kind === "breathe") return "吐纳";
  if (intent.kind === "retreat") return "撤";
  if (intent.kind === "pestle") return "韦陀杵";
  if (intent.kind === "dust") return "迷眼";
  if (intent.kind === "shackle") return "锁链";
  if (intent.kind === "dodge") return "闪避";
  if (intent.kind === "endure") return "霸体";
  if (intent.kind === "sig") return SIGNATURE_BREAK[intent.id as keyof typeof SIGNATURE_BREAK]?.label ?? "绝招";
  return "意图";
}

/** 意图悬浮说明（对战条用） */
export function intentTip(intent: Intent): string {
  if (intent.kind === "strike") return `对你造成 ${intent.damage} 点伤害（先吃格挡）。`;
  if (intent.kind === "charge") return `冲 ${intent.steps} 步；撞上则打 ${intent.damage}。`;
  if (intent.kind === "stake") return "在身前落桩，挡你退路与击退。挡路的桩会先吃你的攻击（低阶 1 次、高阶 2 次）；棍一棍可拆高阶。";
  if (intent.kind === "pull") return `把你往他身边拉 ${intent.steps} 步。`;
  if (intent.kind === "trap") return "在你脚下埋机关，踩中受伤。";
  if (intent.kind === "windup") return "这一息蓄势，下一息往往更重。";
  if (intent.kind === "lunge") return `抢步贴近并打 ${intent.damage}。`;
  if (intent.kind === "swap") return "与你换位，改写站位与撞墙方向。";
  if (intent.kind === "barrage") return `连打 ${intent.hits} 下，每下 ${intent.damage}。`;
  if (intent.kind === "guard") return `获得 ${intent.block} 点架势，打在他身上先被卸掉。`;
  if (intent.kind === "bleedcut") return `打 ${intent.damage}，并给你叠裂创。`;
  if (intent.kind === "counter") return "埋下反击。你打他时会触发回手。";
  if (intent.kind === "mend") return `回 ${intent.heal} 血，并清掉他身上的裂创。`;
  if (intent.kind === "seal") return "封你的脉：下回少劲，并滞步。";
  if (intent.kind === "shatter") return `震掉你约 ${intent.amount} 点格挡。`;
  if (intent.kind === "breathe") return `吐纳回 ${intent.amount} 点敌劲，下息更好出手。`;
  if (intent.kind === "retreat") return `向后撤 ${intent.steps} 格。用进步追上可硬拆。`;
  if (intent.kind === "pestle") return `韦陀杵打 ${intent.damage}，不拆则眩 1。`;
  if (intent.kind === "dust") return "迷眼：下一段你的攻击须贴身才中。";
  if (intent.kind === "shackle") return "锁链：收势若仍贴身则滞步。";
  if (intent.kind === "dodge") return "闪避：你下一张攻击牌落空。走开或先不出刀。";
  if (intent.kind === "endure") return "霸体：你下一张攻击仍能打伤，但击退/拉/眩晕无效。破绽/刺/开缝可硬拆。";
  if (intent.kind === "sig") {
    const sig = SIGNATURE_BREAK[intent.id as keyof typeof SIGNATURE_BREAK];
    return sig ? `${sig.label}：${sig.tip}` : "特色招。";
  }
  return "改变站位。";
}

export function intentMark(intent: Intent): string {
  if (intent.kind === "strike") return String(intent.damage);
  if (intent.kind === "charge") return String(intent.damage);
  if (intent.kind === "lunge") return String(intent.damage);
  if (intent.kind === "barrage") return `${intent.hits}`;
  if (intent.kind === "guard") return "卸";
  if (intent.kind === "bleedcut") return "创";
  if (intent.kind === "counter") return "埋";
  if (intent.kind === "mend") return "药";
  if (intent.kind === "seal") return "封";
  if (intent.kind === "shatter") return "裂";
  if (intent.kind === "breathe") return "纳";
  if (intent.kind === "pull") return "拉";
  if (intent.kind === "trap") return "机";
  if (intent.kind === "windup") return "蓄";
  if (intent.kind === "swap") return "换";
  if (intent.kind === "dodge") return "闪";
  if (intent.kind === "endure") return "霸";
  return "桩";
}

export const WORLD = {
  title: "明手",
  kicker: "港律 · 宫阙 · 缆域 · 潮屿",
  lead: "比武要先亮招。偷袭的人，名册上除名。",
  you: "码头、宫城、街巷、潮屿。人不同，进门处也不同。",
};

export function heartHp(id: HeartId): number {
  return id === "iron" ? 30 : BASE_HP;
}

export function winHeal(id: HeartId): number {
  return id === "breath" ? 4 : 3;
}
