import { buildMetro } from "./metro";
import type { MetroScene } from "./metro";
import { generateLuoyang } from "./luoyangGen";
import { LUOYANG_SUBSCENES } from "./luoyangHub";

export { LUOYANG_BUILDINGS } from "./luoyangMeta";

/** Oversized primary cities — mid/late narrative stages. */
export const METRO_CITIES: Record<string, MetroScene> = {
  huainan: buildMetro({
    id: "huainan",
    name: "淮阴渡",
    kicker: "淮水",
    enter:
      "淮水横在当中。北望中原，南下江左，东去扬州运河，西通洛汴官道。渡口比港湾宽四倍——驿吏、脚夫、茶棚挤在官道两侧。",
    mood: "过了这一渡，港律的潮声就远了。驿烟比潮声近。",
    chapter: "alley",
    w: 64,
    h: 42,
    water: "canal",
    hills: true,
    talkers: {
      f: "ferryman",
      q: "passClerk",
      e: "roadHunter",
      m: "postRider",
      n: "roadCook",
      o: "roadHawker",
      r: "rumorTea",
    },
    npcs: { "1": "thug", "2": "hillBandit" },
    portals: {
      Y: { to: "wharf", at: "9" },
      N: { to: "suqian", at: "S" },
      W: { to: "bozhou", at: "E" },
      E: { to: "yangzhou", at: "W" },
      S: { to: "chuzhou", at: "N" },
    },
    signs: ["北宿迁。西亳州。东扬州。南滁州。无文牒莫闯关。", "淮阴驿。马厩茶棚脚力齐全。"],
    marks: [
      { ch: "2", x: 54, y: 33 },
      { ch: "e", x: 54, y: 32 },
      { ch: "&", x: 12, y: 20 },
      { ch: "&", x: 48, y: 18 },
      { ch: "p", x: 28, y: 22 },
      { ch: "p", x: 30, y: 22 },
      { ch: "l", x: 26, y: 24 },
      { ch: "v", x: 34, y: 24 },
      { ch: ",", x: 32, y: 20 },
      { ch: ",", x: 33, y: 20 },
      { ch: ",", x: 34, y: 20 },
      { ch: "H", x: 10, y: 28 },
    ],
  }),
  changan: buildMetro({
    id: "changan",
    name: "长安·开远门",
    kicker: "长安",
    enter: "开远门外沙土黄。坊巷比港湾宽阔数倍。帝京重心已东移，残阙仍在。",
    mood: "西极。风比人硬。少水，多土。",
    chapter: "court",
    water: "none",
    hills: true,
    talkers: { z: "westGuard", q: "silkMan", m: "passClerk" },
    portals: { E: { to: "tongguan", at: "W" } },
    signs: ["开远门东出潼关。无帖勿行。"],
  }),
  luoyang: generateLuoyang(),
  ...LUOYANG_SUBSCENES,
  bianjing: buildMetro({
    id: "bianjing",
    name: "汴京·御街",
    kicker: "汴京",
    enter: "御街砖缝嵌铜钉。坊市层叠，比港湾大过五倍。西通洛阳，南下淮扬，城外东北有营帐气。",
    mood: "皇恩远。奸臣近。中原偏旷，少水泽。",
    chapter: "court",
    water: "none",
    talkers: {
      w: "worksman",
      e: "eunuch",
      g: "graceMonk",
      r: "rumorTea",
      p: "passClerk",
      n: "grainDoor",
      d: "drumClerk",
      o: "namelessFolk",
    },
    npcs: { "3": "brute" },
    portals: {
      U: { to: "usurpCamp", at: "L" },
      D: { to: "suzhousu", at: "N" },
      W: { to: "luoyang", at: "E" },
      E: { to: "gaoyou", at: "N" },
      K: { to: "shaolin", at: "E" },
    },
    signs: ["北营帐。西洛阳。南宿州。东高邮。西北少室寺。文牒验于城门。"],
  }),
  yangzhou: buildMetro({
    id: "yangzhou",
    name: "扬州·禅智寺前",
    kicker: "扬州",
    enter: "运河在城外响。盐市巷深，楼船影密。西去淮阴，北上汴京，南可达建康。",
    mood: "盐船比官船多。",
    water: "canal",
    talkers: { k: "saltBroker", y: "canalPoet", r: "rumorTea", c: "saltClerk" },
    npcs: { "1": "mob_canal_03" },
    portals: {
      W: { to: "huainan", at: "E" },
      N: { to: "gaoyou", at: "S" },
      S: { to: "jiankang", at: "E" },
    },
    signs: ["北高邮。西淮阴。南建康。盐牙识人。"],
  }),
  jiankang: buildMetro({
    id: "jiankang",
    name: "建康·朱雀航",
    kicker: "建康",
    enter: "朱雀航下江流急。旧都坊巷重重叠叠。北上淮阴，东望扬州，南下苏州临安。",
    mood: "旧都气未散。刀客爱在航边喝酒。",
    water: "north",
    hills: true,
    talkers: { r: "riverBlade", h: "ferryClerk", o: "oldStory" },
    portals: {
      D: { to: "chuzhou", at: "S" },
      E: { to: "yangzhou", at: "S" },
      S: { to: "changzhou", at: "N" },
    },
    signs: ["北滁州。东扬州。南常州。航边有故人。"],
  }),
  suzhou: buildMetro({
    id: "suzhou",
    name: "苏州·阊门",
    kicker: "苏州",
    enter: "阊门外水巷密。园林墙低，丝市声软。北接建康，南通临安钱塘。",
    mood: "丝绸软，刀子不一定软。",
    water: "canal",
    talkers: { v: "silkWife", x: "gardenMonk", r: "rumorTea", b: "silkDebt" },
    portals: {
      D: { to: "wuxi", at: "S" },
      S: { to: "jiaxing", at: "N" },
    },
    signs: ["北无锡。南嘉兴。丝市有私话。"],
  }),
  linan: buildMetro({
    id: "linan",
    name: "临安·钱塘门",
    kicker: "临安",
    enter: "钱塘门外酒旗乱。湖山入城，断桥横水，雷峰塔影压西岸。街市比港湾大过数倍。",
    mood: "江湖气重。圣上的名声在茶里传。水比路多。",
    water: "canal",
    hills: true,
    talkers: { s: "storyman", n: "inkscout", p: "innkeep", r: "rumorTea" },
    npcs: { "1": "thug" },
    portals: { D: { to: "jiaxing", at: "S" } },
    signs: ["钱塘门北出嘉兴。茶楼里有真假圣上。", "西望雷峰。桥下是湖。"],
    marks: [
      // 断桥：路夹在南北水面之间 → 横桥
      { ch: "~", x: 28, y: 18 },
      { ch: "~", x: 29, y: 18 },
      { ch: "~", x: 30, y: 18 },
      { ch: "~", x: 31, y: 18 },
      { ch: "~", x: 32, y: 18 },
      { ch: "~", x: 33, y: 18 },
      { ch: "=", x: 28, y: 19 },
      { ch: "=", x: 29, y: 19 },
      { ch: "=", x: 30, y: 19 },
      { ch: "=", x: 31, y: 19 },
      { ch: "=", x: 32, y: 19 },
      { ch: "=", x: 33, y: 19 },
      { ch: "~", x: 28, y: 20 },
      { ch: "~", x: 29, y: 20 },
      { ch: "~", x: 30, y: 20 },
      { ch: "~", x: 31, y: 20 },
      { ch: "~", x: 32, y: 20 },
      { ch: "~", x: 33, y: 20 },
      // 雷峰塔地标屋（西南空地，避开院墙）
      { ch: "H", x: 12, y: 32 },
      { ch: "~", x: 48, y: 12 },
      { ch: "~", x: 49, y: 12 },
      { ch: "~", x: 50, y: 12 },
      { ch: "~", x: 48, y: 13 },
      { ch: "~", x: 49, y: 13 },
      { ch: "~", x: 50, y: 13 },
    ],
  }),
};
